<?php defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * User: caojiabin
 * Date: 17/2/20
 * Time: 下午2:50
 */
class Controller_Ver1_AntiFraud_TongDun extends AppCore{


    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
    }

    // 保存p
    public function action_SaveBlackBox(){
        $get_data    = $this->_data;
        $black_box   = isset($get_data['black_box']) ? $get_data['black_box'] : '';
        $event_id    = isset($get_data['event_id']) ? $get_data['event_id'] : '';
        $app_os      = App::$os;
        $app_type    = App::$type;
        $user_id     = App::$_token['user_id'];

        if(empty($black_box) or empty($event_id) or empty($app_os) or empty($user_id)){
            $this->response_json('', '5120', '参数错误!');
        }

        if(Model::factory('AntiFraud_TongDun')->add_equipment(['black_box' => $black_box, 'event_id' => $event_id, 'app_os' => $app_os, 'app_type' => $app_type, 'user_id' => $user_id, 'create_time' => time()])){
            $this->response_json('', '1000', '保存成功');
        }

        $this->response_json('', '5121', '保存失败!');
    }
}