<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * Permission: isNum
 * Date: 16/7/29
 * Time: 下午14:54
 */

class Controller_FaceIDAuth extends AdminController {

    protected $permission_array = array(

        'map' => array(
            'List' => array('Detail'),
        ),

    );


    public function before() {

        parent::before(); // TODO: Change the autogenerated stub
    
    }


    public function action_List() {
        

        $page = isset($this->get['page']) ? intval($this->get['page']) : 1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']) : 20;
        $array = array();

        if (isset($this->get['status']) && $this->get['status']) {
            $array['status'] = intval($this->get['status']);
        }

        if (isset($this->get['identity_status']) && $this->get['identity_status']) {
            $array['identity_status'] = intval($this->get['identity_status']);
        }

        if (isset($this->get['mobile']) && $this->get['mobile']) {
            $array['mobile'] = trim($this->get['mobile']);
        }

        if (isset($this->get['name']) && $this->get['name']) {
            $array['name'] = trim($this->get['name']);
        }

        if (isset($this->get['identity_code']) && $this->get['identity_code']) {
            $array['identity_code'] = trim($this->get['identity_code']);
        }

        if (isset($this->get['Photocopym']) && $this->get['Photocopym']) {
            $array['Photocopym'] = $this->get['Photocopym'];
        }

        if (isset($this->get['min_Screen']) && $this->get['min_Screen']) {
            $array['min_Screen'] = $this->get['min_Screen'];
        }

        if (isset($this->get['max_Screen']) && $this->get['max_Screen']) {
            $array['max_Screen'] = $this->get['max_Screen'];
        }
 
        
        $total = Model::factory('User_FaceIDAuth')->getTotal($array);

        $list = Model::factory('User_FaceIDAuth')->getList($array, $perpage, $page); 

         $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
 
        Template::factory('FaceIDAuth/List', array(
                'list' => $list, 
                'pagination' => $pagination, 
                 '_status' => Model::factory('User_FaceIDAuth')->status_array,
                '_identity_status' => Model::factory('User_FaceIDAuth')->identity_status_array,
            )
        )->response();

    }

    //详情
    public function action_Detail() {


        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']) : 0;
        $faceidauth = Model::factory('User_FaceIDAuth')->getOne($id);

        if (empty($faceidauth)) {
            Template::factory()->message(
                array(
                    'type' => 'error',
                    'title' => '信息不存在',
                    'message' => '信息不存在或已经被删除.',
                    'back' => TRUE,)
            );
        }

       
         // 用户基本信息
       
        $user = Model::factory('User')->getInformation($faceidauth['user_id']);
 
        //获取用户faceidauth照片信息
        $faceid_auth = Model::factory('User')->getFaceIdAuth($faceidauth['user_id'],$faceidauth['identity_code']);

        $array = array_merge($user,$faceid_auth);

        
        if(!isset($identity_face['status']) || $identity_face['status'] == false){
            $message = array('type' => 'error', 'message' => '身份证图片异常,请联系管理员');
        }

        Template::factory('FaceIDAuth/Detail', array(
                'faceidauth' => $faceidauth,
                'user' => $array,
                '_status' => Model::factory('User_FaceIDAuth')->status_array,
                '_identity_status' => Model::factory('User_FaceIDAuth')->identity_status_array,
                'message' => $message,
            )
        )->response();
    }
}
