<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * Permission: majin
 * Date: 16/1/11
 * Time: 上午9:20
 *
 * 菜单管理
 *
 */
class Controller_Admin_Upload extends AdminController {

    //权限映射
    var $permission_array = array(
        'map' => array(
                    'List' => array('Index','File')
                )
    );



    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
    }


    public function action_Index() {
        $this->action_List();
    }



    public function action_List() {

        $page = isset($this->get['page']) ? intval($this->get['page']):1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']):20;
        $array = array();



        if(array_key_exists('user_id',$this->get) && $this->get['user_id'] ) {
            $array['user_id'] = intval($this->get['user_id']);
        }
        if(array_key_exists('username',$this->get) && $this->get['username']) {
            $array['username'] = trim($this->get['username']);
        }
        if(array_key_exists('email',$this->get) && $this->get['email']) {
            $array['email'] = trim($this->get['email']);
        }
        if(array_key_exists('time_start',$this->get)) {
            $array['time_start'] = trim($this->get['time_start']);
        }
        if(array_key_exists('time_end',$this->get)) {
            $array['time_end'] = trim($this->get['time_end']);
        }

        $total = Model::factory('Admin_Upload')->get_total($array);
        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
        $list = Model::factory('Admin_Upload')->get_list($array, $perpage , $page);

        Template::factory('Admin/Upload/List',array(
                'list'=>$list,
                'pagination'=>$pagination,
            )
        )->response();
    }




    public function action_File(){
        SecurityFile::$config['security_path']='';
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $data  = Model::factory('Admin_Upload')->get_one($id);
        if(empty($data)){
            Template::factory()->message(
                array(
                    'type' => 'error',
                    'title' => '信息不存在',
                    'message' => '信息不存在或已经被删除.',
                    'back' => TRUE,)
            );
        }
        if($data['file']) {
            SecurityFile::response($data['file']);
        }
    }



}