<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * Permission: majin
 * Date: 15/12/24
 * Time: 上午10:33
 *
 * 权限管理
 *
 */

class Controller_Admin_Permission extends AdminController {

    //权限映射
    var $permission_array =array(
        'map'=> array(
            'List' => array('Index','Add','Edit','Delete','GroupList','GroupAdd','GroupEdit','GroupDelete')
        )
    );

    var $permission_group = array();



    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
        $this->permission_group = Model::factory('Admin_Permission')->getGroupAll();
    }


    public function action_Index() {
        $this->action_List();
    }


    //权限列表
    public function action_List() {

        $page = isset($this->get['page']) ? intval($this->get['page']):1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']):20;
        $array = array();
        if(isset($this->get['group_id'])) {
            $array['group_id'] = intval($this->get['group_id']);
        }

        $total = Model::factory('Admin_Permission')->getTotal($array);
        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
        $list = Model::factory('Admin_Permission')->getList($array, $perpage , $page);

        Template::factory('Admin/Permission/List',array(
                'list'=>$list,
                'permission_group'=>$this->permission_group,
                'pagination'=>$pagination,
            )
        )->response();


    }

    //添加权限
    public function action_Add() {
        $message = NULL;
        if(isset($this->post['submit'])) {
            $valid = Validation::factory($this->post)
                ->rule('group_id','numeric')
                ->rule('name','not_empty');
            if($valid->check()) {
                $add = Model::factory('Admin_Permission')->create(array(
                    'name'=>$this->post['name'],
                    'controller' => $this->post['controller'],
                    'action' => $this->post['action'],
                    'description'=>$this->post['description'],
                    'sort'=>$this->post['sort'],
                    'group_id'=>$this->post['group_id'],
                ));
                if($add) {
                    $message = array('type' => 'success', 'message' => '添加成功.');
                }else {
                    $message = array('type' => 'error', 'message' => '添加失败.');
                }
            }else {
                $message = array('type' => 'error', 'message' => '添加失败,请查看是否有必填信息未填.');
            }
        }

        Template::factory('Admin/Permission/Add',array(
            'message'=>$message,
            'permission_group' => $this->permission_group,
        ))->response();


    }

    //修改权限
    public function action_Edit() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $data  = Model::factory('Admin_Permission')->getOne($id);
        if(!$data) {
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'信息不存在',
                    'message'=>'信息不存在或已经被删除.',
                    'back'=>TRUE,)
            );
        }
        if(isset($this->post['group_id']) && $this->post['group_id']>0){
            if( !Model::factory('Admin_Permission')->getGroup($this->post['group_id'])){
                Template::factory()->message(
                    array(
                        'type'=>'error',
                        'title'=>'权限组不存在',
                        'message'=>'权限组不存在或已经被删除.',
                        'back'=>TRUE,)
                );
            }
        }

        if(isset($this->post['submit'])) {
            //var_dump($this->post);
            $valid = Validation::factory($this->post)
                ->rule('group_id','numeric')
                ->rule('name','not_empty');
            if($valid->check()) {
                $edit = Model::factory('Admin_Permission')->update($id,array(
                    'name'=>$this->post['name'],
                    'controller'=>$this->post['controller'],
                    'action'=>$this->post['action'],
                    'sort'=>$this->post['sort'],
                    'description'=>$this->post['description'],
                    'group_id'=>$this->post['group_id'],
                ));
                if($edit) {
                    $message = array('type' => 'success', 'message' => '更新成功.');
                    $data  = Model::factory('Admin_Permission')->getOne($id);//更新输出数据
                }else {
                    $message = array('type' => 'error', 'message' => '更改失败,数据异常.');
                }
            }else {
                $message = array('type' => 'error', 'message' => '更改失败,请查看是否有必填信息未填.');
            }
        }

        Template::factory('Admin/Permission/Edit',array(
            'message'=>$message,
            'permission_group' => $this->permission_group,
            'data'=>$data,
        ))->response();
    }

    public function action_Delete() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $rs  = Model::factory('Admin_Permission')->getOne($id);
        if(!$rs){
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'信息不存在',
                    'message'=>'信息不存在或已经被删除.',
                    'back'=>TRUE,)
            );
        }
        $del = Model::factory('Admin_Permission')->delete($id);
        if($del){
            Template::factory()->message(
                array(
                    'type'=>'success',
                    'title'=>'删除成功',
                    'message'=>'权限:'.$rs['name'].' 被成功删除.',
                    'redirect'=> $this->request->referrer()? $this->request->referrer() :'/'.$this->controller.'/List',
                    'redirect_time'=>3,
                    'back'=>FALSE)
            );
        }
        Template::factory()->message(
            array(
                'type'=>'error',
                'title'=>'删除失败',
                'message'=>'权限:'.$rs['name'].' 删除未成功,请核实或联系技术人员处理.',
                'back'=>TRUE,)
        );
    }


    //组列表
    public function action_GroupList() {

        $page = isset($this->get['page']) ? intval($this->get['page']):1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']):20;
        $total = Model::factory('Admin_Permission')->getGroupTotal();
        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
        $list = Model::factory('Admin_Permission')->getGroupList(array(), $perpage , $page);

        Template::factory('Admin/Permission/GroupList',array(
                'list'=>$list,
                'pagination'=>$pagination,
            )
        )->response();
    }


    //组添加
    public function action_GroupAdd() {
        $message = NULL;
        if(isset($this->post['submit'])) {
            $valid = Validation::factory($this->post)->rule('name','not_empty')->rule('sort','numeric');
            if($valid->check()) {
                $add = Model::factory('Admin_Permission')->createGroup(array(
                    'name'=>$this->post['name'],
                    'description'=>$this->post['description'],
                    'sort'=>$this->post['sort'],
                ));
                if($add) {
                    $message = array('type' => 'success', 'message' => '添加成功.');
                }else {
                    $message = array('type' => 'error', 'message' => '添加失败.');
                }
            }else {
                $message = array('type' => 'error', 'message' => '添加失败,请查看是否有必填信息未填.');
            }
        }

        Template::factory('Admin/Permission/GroupAdd',array(
            'message'=>$message,
        ))->response();
    }


    //组更改
    public function action_GroupEdit() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $data  = Model::factory('Admin_Permission')->getGroup($id);
        if(!$data) {
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'信息不存在',
                    'message'=>'信息不存在或已经被删除.',
                    'back'=>TRUE,)
            );
        }

        if(isset($this->post['submit'])) {
            $valid = Validation::factory($this->post)->rule('name','not_empty');
            if($valid->check()) {
                $edit = Model::factory('Admin_Permission')->updateGroup($id,array(
                    'name'=>$this->post['name'],
                    'sort'=>$this->post['sort'],
                    'description'=>$this->post['description'],
                ));
                if($edit) {
                    $message = array('type' => 'success', 'message' => '更新成功.');
                    $data  = Model::factory('Admin_Permission')->getGroup($id);//更新输出数据
                }else {
                    $message = array('type' => 'error', 'message' => '更改失败,数据异常.');
                }
            }else {
                $message = array('type' => 'error', 'message' => '更改失败,请查看是否有必填信息未填.');
            }
        }

        Template::factory('Admin/Permission/GroupEdit',array(
            'message'=>$message,
            'data'=>$data,
        ))->response();
    }


    //组删除
    public function action_GroupDelete() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $rs  = Model::factory('Admin_Permission')->getGroup($id);
        if(!$rs){
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'信息不存在',
                    'message'=>'信息不存在或已经被删除.',
                    'back'=>TRUE,)
            );
        }
        $son  = Model::factory('Admin_Permission')->getTotal($id);
        if($son>0){
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'删除失败',
                    'message'=>'该组下存在权限项.',
                    'back'=>TRUE,)
            );
        }
        $del = Model::factory('Admin_Permission')->deleteGroup($id);
        if($del){
            Template::factory()->message(
                array(
                    'type'=>'success',
                    'title'=>'删除成功',
                    'message'=>'权限组:'.$rs['name'].' 被成功删除.',
                    'redirect'=> $this->request->referrer()? $this->request->referrer() :'/'.$this->controller.'/GroupList',
                    'redirect_time'=>3,
                    'back'=>FALSE)
            );
        }
        Template::factory()->message(
            array(
                'type'=>'error',
                'title'=>'删除失败',
                'message'=>'权限组:'.$rs['name'].' 删除未成功,请核实或联系技术人员处理.',
                'back'=>TRUE,)
        );

    }


}