<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/1/12
 * Time: 下午9:43
 */
class Controller_Bank extends AdminController {


    //权限映射
    public $permission_array = array(
        'map' => array(
            'List' => array('Index', 'Add', 'Edit')
        )
    );

    public $_status = array();

    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
        $this->_status = Model::factory('Bank')->status_array;
    }


    public function action_Index() {
        $this->action_List();
    }


    //列表
    public function action_List() {

        $page = isset($this->get['page']) ? intval($this->get['page']) : 1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']) : 20;
        $array = array();
        if(isset($this->get['name']) && $this->get['name']){
            $array['name'] = trim($this->get['name']);
        }

        $total = Model::factory('Bank')->getTotal($array);
        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
        $list = Model::factory('Bank')->getList($array, $perpage, $page);

        Template::factory('Bank/List', array(
                'list' => $list,
                'pagination' => $pagination,
                '_status' => $this->_status,
            )
        )->response();

    }


    //添加
    public function action_Add() {
        $message = NULL;
        if (isset($this->post['submit'])) {
            $valid = Validation::factory($this->post)->rule('name','not_empty')->rule('code','not_empty');
            if($valid->check()) {
                $add = Model::factory('Bank')->create(array(
                    'name' => $this->post['name'],
                    'code' => $this->post['code'],
                    'unionpay_code' => $this->post['unionpay_code'],
                    'status' => intval($this->post['status']),
                    'rank' => intval($this->post['rank']),
                ));
                if ($add) {
                    $message = array('type' => 'success', 'message' => '添加成功.');
                    $this->admin()->opteration_log('添加银行  名称:'.$this->post['name']);
                } else {
                    $message = array('type' => 'error', 'message' => '添加失败.');
                }
            } else {
                $message = array('type' => 'error', 'message' => '添加失败,请查看是否有必填信息未填.');
            }
        }
        Template::factory('Bank/Add', array(
            'message' => $message,
            '_status' => $this->_status,
        ))->response();

    }


    //修改
    public function action_Edit() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']) : 0;
        $data = Model::factory('Bank')->get_one($id);
        if (!$data) {
            Template::factory()->message(
                array(
                    'type' => 'error',
                    'title' => '信息不存在',
                    'message' => '信息不存在或已经被删除.',
                    'back' => TRUE,)
            );
        }

        if (isset($this->post['submit'])) {
            if ($this->post['name']) {
                $edit = Model::factory('Bank')->update($id, array(
                    'name' => $this->post['name'],
                    'code' => $this->post['code'],
                    'unionpay_code' => $this->post['unionpay_code'],
                    'status' => intval($this->post['status']),
                    'rank' => intval($this->post['rank']),
                ));
                if ($edit) {
                    $message = array('type' => 'success', 'message' => '更新成功.');
                    $this->admin()->opteration_log('更改银行 id:'.$data['id'].' 名称:'.$data['name'],trim($this->post['admin_log_message']));
                    $data = Model::factory('Bank')->get_one($id);//更新输出数据
                } else {
                    $message = array('type' => 'error', 'message' => '更改失败,数据异常.');
                }
            } else {
                $message = array('type' => 'error', 'message' => '更改失败,请查看是否有必填信息未填.');
            }
        }


        Template::factory('Bank/Edit', array(
            'message' => $message,
            'data' => $data,
            '_status' => $this->_status,
        ))->response();
    }




}