<?php
defined('SYSPATH') or die('No direct script access.');

/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/1/28
 * Time: 下午5:19
 *
 * 短信模板管理
 */
class Controller_SMSProvider extends AdminController
{

    protected $permission_array = array(

        'map' => array(
            'List' => array('Add', 'Edit'),
        ),

    );

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }


    public function action_List()
    {
        $page = isset($this->get['page']) ? intval($this->get['page']) : 1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']) : 20;
        $array = array();

        $total = Model::factory('SMS_Provider')->getTotal($array);
        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
        $list = Model::factory('SMS_Provider')->getList($array, $perpage, $page);

        Template::factory('SMS/Provider/List', array(
                'list' => $list,
                'pagination' => $pagination,
            )
        )->response();

    }


    //添加
    public function action_Add()
    {
        $message = null;
        if (isset($this->post['submit'])) {
            $name = mb_substr($this->post['name'], 0, 25);
            $provider = mb_substr($this->post['provider'], 0, 25);
            $desc = mb_substr($this->post['desc'], 0, 255);

            $new_id = Model::factory('SMS')->create(array(
                'name' => $name,
                'provider' => $provider,
                'desc' => $desc,
            ));
            if ($new_id) {
                $message = array('type' => 'success', 'message' => '添加成功.');
                $this->admin()->opterationLog('添加短信服务商  ID:' . $new_id . ' 名称:' . $name);
            } else {
                $message = array('type' => 'error', 'message' => '添加失败.,请查看是否有必填信息未填.');
            }
        }

        Template::factory('SMS/Provider/Add', array(
            'message' => $message,
        ))->response();

    }


    public function action_Edit()
    {
        $message = null;
        $id = isset($this->get['id']) ? intval($this->get['id']) : 0;
        $data = Model::factory('SMS_Provider')->getOne($id);
        if (!$data) {
            Template::factory()->message(
                array(
                    'type' => 'error',
                    'title' => '信息不存在',
                    'message' => '信息不存在或已经被删除.',
                    'back' => true,
                )
            );
        }

        if (isset($this->post['submit']) && $this->post['submit']) {
            $name = mb_substr($this->post['name'], 0, 25);
            $provider = mb_substr($this->post['provider'], 0, 25);
            $desc = mb_substr($this->post['desc'], 0, 255);

            $update_array = array(
                'name' => $name,
                'provider' => $provider,
                'desc' => $desc,
            );
            $update = Model::factory('SMS')->update($id, $update_array);
            if ($update) {
                $this->admin()->opterationLog('更改短信服务商 ID' . $id, trim($this->post['admin_log_message']));
                $data = Model::factory('SMS')->getOne($id);
                $message = array('type' => 'success', 'message' => '更改成功.');
            } else {
                $message = array('type' => 'error', 'message' => '更改失败.');
            }
        }

        Template::factory('SMS/Provider/Edit', array(
            'message' => $message,
            'data' => $data,
        ))->response();
    }

}
