<?php
defined('SYSPATH') or die('No direct script access.');

/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/5/31
 * Time: 上午11:11
 * 配置信息
 */
class Controller_Ver1_Settings extends AppCore
{

    protected $_check_token = false;
    protected $_check_user = false;

    protected $_settings = [];//配置数组


    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub

        //CACHE ----[BEGIN]
        $ca = Lib::factory('TCCache_Settings')->uri(Request::current()->uri())->get();//CACHE GET
        if ($ca) {
            $response_array = $ca;
            $this->response_json($response_array, "1000", "预制配置");
        }
        //CACHE ----[END]
    }


    protected function common()
    {
        //银行列表
        $bank = Model::factory('Bank')->get_all(Model_Bank::STATUS_VALID);
        if ($bank) {
            $this->_settings['bank'] = $bank;
        }


        $this->_settings['verify_code'] = Def::VERIFY_CODE;//验证码开关


        $this->_settings['tab_bar'][] = [
            'selected_color' => '',
            'selected_img' => 'http://a-cdn.timecash.cn/banner/inst/tab/icon_jiekuan_pre.png',
            'img' => 'http://a-cdn.timecash.cn/banner/inst/tab/icon_jiekuan_nor.png',
            'title' => '首页',
        ];

        $this->_settings['tab_bar'][] = [
            'selected_color' => '',
            'selected_img' => 'http://a-cdn.timecash.cn/banner/inst/tab/icon_huankuan_pre.png',
            'img' => 'http://a-cdn.timecash.cn/banner/inst/tab/icon_huankuan_nor.png',
            'title' => '还款',
        ];

        $this->_settings['tab_bar'][] = [
            'selected_color' => '',
            'selected_img' => 'http://a-cdn.timecash.cn/banner/inst/tab/icon_gerenzhongxin_prer.png',
            'img' => 'http://a-cdn.timecash.cn/banner/inst/tab/icon_gerenzhongxin_nor.png',
            'title' => '个人中心',
        ];


    }


    /**
     *  公用
     */
    public function action_Index()
    {
        $this->common();
        Lib::factory('TCCache_Settings')->uri(Request::current()->uri())->set($this->_settings);//CACHE ----- [WRITE]

        $this->response_json($this->_settings, "1000", "预制配置");
    }


    /**
     *  android
     */
    public function action_Android()
    {
        $this->common();
        $config = Kohana::$config->load('app')->get('android');
        $ver = isset($config['ver']) ? $config['ver'] : '1.0';
        $update = isset($config['update']) ? $config['update'] : '';
        $install = isset($config['install']) ? $config['install'] : null;
        $must_upgrade = isset($config['must_upgrade']) ? (string)$config['must_upgrade'] : '0';
        $this->_settings['app']['ver'] = $ver;
        $this->_settings['app']['update'] = $update;
        $this->_settings['app']['must_upgrade'] = $must_upgrade;
        if ($install) {
            $this->_settings['app']['install'] = $install;
        }

        Lib::factory('TCCache_Settings')->uri(Request::current()->uri())->set($this->_settings);//CACHE ----- [WRITE]

        $this->response_json($this->_settings, "1000", "预制配置");
    }


    /**
     *  ios
     */
    public function action_IOS()
    {
        $this->common();
        $config = Kohana::$config->load('app')->get('ios');
        $ver = isset($config['ver']) ? $config['ver'] : '1.0';
        $develop_ver = isset($config['develop_ver']) ? $config['develop_ver'] : $ver;
        $update = isset($config['update']) ? $config['update'] : '';
        $install = isset($config['install']) ? $config['install'] : null;
        $must_upgrade = isset($config['must_upgrade']) ? (string)$config['must_upgrade'] : '0';
        $this->_settings['app']['ver'] = $ver;
        $this->_settings['app']['update'] = $update;
        $this->_settings['app']['must_upgrade'] = $must_upgrade;
        $this->_settings['app']['develop_ver'] = $develop_ver;
        if ($install) {
            $this->_settings['app']['install'] = $install;
        }

        Lib::factory('TCCache_Settings')->uri(Request::current()->uri())->set($this->_settings);//CACHE ----- [WRITE]

        $this->response_json($this->_settings, "1000", "预制配置");
    }


    /**
     *  微信
     */
    public function action_Wechat()
    {
        $this->common();
        Lib::factory('TCCache_Settings')->uri(Request::current()->uri())->set($this->_settings);//CACHE ----- [WRITE]

        $this->response_json($this->_settings, "1000", "预制配置");
    }


}