<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * User: wangchao
 * Date: 2017/11/14
 * Time: 下午2:43
 *
 *
 * 扣款队列 列表
 *
 */
class Controller_Queue_Deduct extends AdminController {

    protected $deduct_provider = NULL;
    protected $deduct_core = NULL;

    public $model = NUll;
    public $model_name = 'Deduct_Umpay';

    protected $_status = NULL;
    public $_page = 1;
    public $_perpage = 2;


    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
//        $this->_status = Model::factory('Order')->status_array;
//        $this->_type = Model::factory('Order')->type_array;
        $this->_page = isset($this->get['page']) ? intval($this->get['page']) : 1;
        $this->_perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']) : 100;
    }

    //处理中列表
    public function action_List(){

        if(isset($this->get['order_no']) && $this->get['order_no'] ) {
            $array['order_no'] = trim($this->get['order_no']);
            $array['join'] = array('order');
        }
        if(isset($this->get['mobile']) && $this->get['mobile'] ) {
            $array['mobile'] = trim($this->get['mobile']);
            $array['join'] = array('order');
        }

        if(isset($this->get['identity_code']) && $this->get['identity_code'] ) {
            $array['identity_code'] = trim($this->get['identity_code']);
            $array['join'] = array('order');
        }
        $array['Process'] = 1;

        $this->coreList($array, $this->_perpage, $this->_page, 'Queue/Deduct/_CoreList', array('subject' => '扣款队列'),'处理中列表');
    }

    //扣款成功列表
    public function action_SuccessList(){
        if(isset($this->get['order_no']) && $this->get['order_no'] ) {
            $array['order_no'] = trim($this->get['order_no']);
            $array['join'] = array('order');
        }
        if(isset($this->get['mobile']) && $this->get['mobile'] ) {
            $array['mobile'] = trim($this->get['mobile']);
            $array['join'] = array('order');
        }

        if(isset($this->get['identity_code']) && $this->get['identity_code'] ) {
            $array['identity_code'] = trim($this->get['identity_code']);
            $array['join'] = array('order');
        }
        $array['Success'] = 1;
        $this->coreList($array, $this->_perpage, $this->_page, 'Queue/Deduct/_CoreList', array('subject' => '扣款队列'),'扣款成功列表');
    }

    //扣款失败列表
    public function action_FailList(){

        if(isset($this->get['order_no']) && $this->get['order_no'] ) {
            $array['order_no'] = trim($this->get['order_no']);
            $array['join'] = array('order');
        }
        if(isset($this->get['mobile']) && $this->get['mobile'] ) {
            $array['mobile'] = trim($this->get['mobile']);
            $array['join'] = array('order');
        }

        if(isset($this->get['identity_code']) && $this->get['identity_code'] ) {
            $array['identity_code'] = trim($this->get['identity_code']);
            $array['join'] = array('order');
        }
        $array['Fail'] = 1;
        $this->coreList($array, $this->_perpage, $this->_page, 'Queue/Deduct/_CoreList', array('subject' => '扣款队列'),'扣款失败列表');
    }

    //复用查询
    public function coreList($array,$perpage = 100, $page = 1, $tpl = NULL, $data = NULL ,$title = null)
    {
        $total = Model::factory('Queue_Deduct')->getTotal($array);

        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));

        $list = Model::factory('Queue_Deduct')->getList($array,$perpage, $page);

        if ($tpl === NULL) {
            $tpl = 'Queue/Deduct/_CoreList';
        }
        Template::factory($tpl, array(
                'total' => $total,
                'list' => $list,
                '_status' => $this->_status,
                'pagination' => $pagination,
                'title' => $title
            )
        )->set($data)->response();
    }

}
