<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/5/25
 * Time: 下午3:43
 *
 * 地理位置
 */
class Controller_Ver1_Location extends AppCore{

    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
        $this->model['step'] = Model::factory('CreditInfo_Step');;
        $this->model['gps'] = Model::factory('Location_Gps');
        $this->model['baidumap'] = Model::factory('Location_BaiduMap');
    }

    public function action_Log(){

        if( !isset($this->_data['gps']) && !isset($this->_data['baidu_map']) ){
            $this->response_json(array(),"4005","参数错误");
        }

        $gps_id = 0;
        $baidumap_id = 0;

        //gps定位
        if (isset($this->_data['gps']['longitude']) && isset($this->_data['gps']['latitude']) && is_numeric($this->_data['gps']['longitude']) && is_numeric($this->_data['gps']['latitude'])) {
            $gps_id = $this->model['gps']->create(array(
                    'user_id' => App::$_token['user_id'],
                    'longitude' => $this->_data['gps']['longitude'],
                    'latitude' => $this->_data['gps']['latitude'])
            );
        }
        //百度地图
        if (isset($this->_data['baidu_map']['lng']) && isset($this->_data['baidu_map']['lat']) && is_numeric($this->_data['baidu_map']['lng']) && is_numeric($this->_data['baidu_map']['lat']) ) {
            $baidumap_id = $this->model['baidumap']->create(array(
                    'user_id' => App::$_token['user_id'],
                    'lng' => $this->_data['baidu_map']['lng'],
                    'lat' => $this->_data['baidu_map']['lat'],
                    'formatted_address' => isset($this->_data['baidu_map']['formatted_address']) ? $this->_data['baidu_map']['formatted_address'] : '',
                    'country' => isset($this->_data['baidu_map']['country']) ? $this->_data['baidu_map']['country'] : '',
                    'province' => isset($this->_data['baidu_map']['province']) ? $this->_data['baidu_map']['province'] : '',
                    'city' => isset($this->_data['baidu_map']['city']) ? $this->_data['baidu_map']['city'] : '',
                    'district' => isset($this->_data['baidu_map']['district']) ? $this->_data['baidu_map']['district'] : '',
                    'business_circle' => isset($this->_data['baidu_map']['business_circle']) ? $this->_data['baidu_map']['business_circle'] : '',
                    'street' => isset($this->_data['baidu_map']['street']) ? $this->_data['baidu_map']['street'] : '',
                    'street_number' => isset($this->_data['baidu_map']['street_number']) ? $this->_data['baidu_map']['street_number'] : '',
                )
            );
        }


        if($gps_id>0 || $baidumap_id>0){
            $rs = $this->model['step']->get_one(App::$_token['user_id']);
            if( isset($rs[Model_CreditInfo_Step::LOCATION]) && $rs[Model_CreditInfo_Step::LOCATION] == Model_CreditInfo_Step::INCOMPLETE ){
                Model::factory('CreditInfo_Step')->change(App::$_token['user_id'],['status' => Model_CreditInfo_Step::COMPLETE,'pass_time' => time()],Model_CreditInfo_Step::LOCATION);
            }
            $this->model['step']->value_add(App::$_token['user_id'],Model_CreditInfo_Step::LOCATION_COUNT,1);
        }

        $this->response_json(array(),"1000","提交完成");
    }



}