<?php defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/6/21
 * Time: 下午8:22
 */
class Controller_Ver1_AD extends AppCore{
    protected $_check_token = FALSE;
    protected $_check_user = FALSE;

    protected $response_array =[];

    protected $tester = [722030, 11160, 505471];//聂淑昆 彭文鑫 张战良
    protected $tester_ad_id = 33;//上线测试，用于tester提前看广告id


    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
        //CACHE ----[BEGIN]
        $ca = Lib::factory('TCCache_AD')->uri(Request::current()->uri())->get();//CACHE GET
        if($ca){
            $response_array = $ca;
            $this->ad_for_tester($response_array['top_banner']);

            $this->response_json($response_array,"1000","广告展示");
        }
        //CACHE ----[END]
    }

    //只有3.0.1以后的测试人员可以看到测试banner
    public function ad_for_tester(& $top_banner){
        if(App::$_token['user_id'] > 0 && in_array(App::$_token['user_id'], $this->tester)){
            $test = Model::factory('AD')->getOne($this->tester_ad_id);
            array_unshift($top_banner, $test);
        }

    }

    // 获取首页banner图
    public function action_Banner(){

        // 实例化
        $bannerModel = Model::factory('AD');
        $bannerData = $bannerModel->getBanner();

        // 广告
        $top_banner = array();
        $boot_banner = array();
        $top_banner2 = array();

        if($bannerData){
            foreach ($bannerData as $banner){
                $_ad = array(
                    'id'            => $banner['id'] . '',
                    'img'           => $banner['img'],
                    'target'        => $banner['target'],       //如果是系统内页面 timecash://app/loan
                    'subject'       => $banner['subject'],
                    'summary'       => $banner['summary'],
                    'rank'          => $banner['rank'],         //显示顺序
                    'start_time'    => $banner['start_time'],   //发布时间
                    'end_time'      => $banner['end_time'],     //结束时间
                    'stop_sec'      => $banner['stop_sec'],     //字多的可以停止十秒 参考
                );
                if($banner['type'] == 1){
                    // top
                    $top_banner[] = $_ad;
                }elseif ($banner['type'] == 2){
                    // boot
                    $boot_banner[] = $_ad;
                }elseif ($banner['type'] == 3){
                    $top_banner2[] = $_ad;
                }

            }
        }


        // 组合并返回数据
        $response_array = array(
            'top_banner'=>$top_banner,
            'top_banner2'=> $top_banner2,
            'boot_banner'=>$boot_banner,
        );


        Lib::factory('TCCache_AD')->uri(Request::current()->uri())->set($response_array);//CACHE ----- [WRITE]

        $response_array['_db_read'] = "1";
        $this->response_json($response_array,"1000","广告展示");
    }







    public function _load(array $app_ids){


        $banners = Model::factory('AD')->get_by_app_id($app_ids);

        // 广告
        $top_banner = array();
        $boot_banner = array();
        $top_banner2 = array();

        if($banners){
            foreach ($banners as $banner){
                $_ad = array(
                    'id'            => $banner['id'] . '',
                    'img'           => $banner['img'],
                    'target'        => $banner['target'],       //如果是系统内页面 timecash://app/loan
                    'subject'       => $banner['subject'],
                    'summary'       => $banner['summary'],
                    'rank'          => $banner['rank'],         //显示顺序
                    'start_time'    => $banner['start_time'],   //发布时间
                    'end_time'      => $banner['end_time'],     //结束时间
                    'stop_sec'      => $banner['stop_sec'],     //字多的可以停止十秒 参考
                );
                if($banner['type'] == 1){
                    // top
                    $top_banner[] = $_ad;
                }elseif ($banner['type'] == 2){
                    // boot
                    $boot_banner[] = $_ad;
                }elseif ($banner['type'] == 3){
                    $top_banner2[] = $_ad;
                }

            }
        }

        // 组合并返回数据
        $this->response_array = array(
            'top_banner'=>$top_banner,
            'top_banner2'=> $top_banner2,
            'boot_banner'=>$boot_banner,
        );

    }


    public function action_Android(){
        $app_id='android';
        $this->_load([Model_AD::ALL_APP_ID,$app_id]);
        Lib::factory('TCCache_AD')->uri(Request::current()->uri())->set($this->response_array);//CACHE ----- [WRITE]
        $this->response_array['_db_read'] = "1";

        $this->response_json($this->response_array,"1000","广告展示");
    }



    public function action_IOS(){
        $app_id='ios';
        $this->_load([Model_AD::ALL_APP_ID,$app_id]);
        Lib::factory('TCCache_AD')->uri(Request::current()->uri())->set($this->response_array);//CACHE ----- [WRITE]
        $this->response_array['_db_read'] = "1";
        $this->response_json($this->response_array,"1000","广告展示");
    }



    public function action_Wechat(){
        $app_id='wechat';
        $this->_load([Model_AD::ALL_APP_ID,$app_id]);
        Lib::factory('TCCache_AD')->uri(Request::current()->uri())->set($this->response_array);//CACHE ----- [WRITE]
        $this->response_array['_db_read'] = "1";

        $this->response_json($this->response_array,"1000","广告展示");

    }








}
