<?php defined('SYSPATH') or die('No direct script access.');

/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/6/21
 * Time: 下午8:22
 */
class Controller_Ver1_AntiFraud_BaiRong extends AppCore
{


    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    // 保存
    public function action_SaveSwiftNumber()
    {
        $get_data = $this->_data;
        $swift_number = isset($get_data['swift_number']) ? $get_data['swift_number'] : '';
        $event = isset($get_data['event']) ? $get_data['event'] : '';
        $gid = isset($get_data['gid']) ? $get_data['gid'] : '';
        $app_os = App::$os;
        $app_type = App::$type;
        $user_id = App::$_token['user_id'];

        if (empty($swift_number) or empty($event) or empty($app_os) or empty($user_id)) {
            $this->response_json('', '5120', '参数错误!');
        }


        if (Model::factory('AntiFraud_BaiRong')->add_equipment([
            'swift_number' => $swift_number, 'event' => $event, 'app_os' => $app_os, 'app_type' => $app_type,
            'user_id' => $user_id, 'gid' => $gid, 'create_time' => time(),
        ])
        ) {
            $this->response_json('', '1000', '保存成功');
        }

        $this->response_json('', '5121', '保存失败!');
    }
}