<?php
defined('SYSPATH') or die('No direct script access.');

/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/5/13
 * Time: 下午6:19
 */
class Controller_Ver1_TestRedis extends Controller
{

    public $model;

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }


    public function action_Flush()
    {
        $user_id = (int)$this->request->query('user_id');
        $key = (string)$this->request->query('key');
        $redis = Redis_Hash::instance();
        //Lib::factory('TCCache_TokenSession')->token_id(7157605)->set('');
        if ($user_id > 0) {
            echo '<pre>user_id:' . $user_id . '</pre> <hr>';
            $rs = $redis->del('user@' . $user_id);
            if ($rs) {
                echo '<p>用户ID:' . $user_id . '缓存已经清除</p>';
            }
        }
        if ($key) {
            echo '<pre>key:' . $key . '</pre> <hr>';
            $rs = $redis->del($key);
            if ($rs) {
                echo '<p>' . $key . '缓存已经清除</p>';
            }
        }
    }


    public function action_Get()
    {
        $key = $this->request->query('key');
        $redis = Redis_Hash::instance();
        echo '<pre>key:' . $key . '</pre> <hr>';
        var_dump($redis->get($key));
    }


}









