<?php
header("Content-Type: text/html; charset=UTF-8");
define("STATUS", "1");    //1正式 2测试
class BaiRong_CONFIG {
    private static $configStr;   //配置信息
    private static $titleStr;    //表头
    private static $allDataArr = array();  //数据信息

    public static $account = 'kuaijin';
    public static $password = 'kuaijin';
    public static $apicode = '3000128';
    //pufubao测试账户
    public static $pufubao_account = 'kuaijinAPI';
    public static $pufubao_password = 'kuaijinAPI';
    public static $pufubao_apicode = '3000662';
    public static $login_url = 'https://api.100credit.cn/bankServer2/user/login.action';
    public static $data_url = 'https://api.100credit.cn/bankServer2/data/terData.action';
    //public static $data_one_url = 'https://api.100credit.cn/HainaApi/data/getData.action';
    public static $data_one_url = 'https://api.100credit.cn/trinity_force/v1/get_data';

    //表头
    public static $headerTitle = array();
    //数据
    public static $targetList = array();
    //获取info.txt
    public static function init(){
        if(STATUS == 2){
            self::getInfoTxt();
        }
    }
    public static function isDebug() {
        return false;//false 只输出csv
    }

    public static function getInfoTxt() {
        $file = 'info.txt';
        $f = fopen($file,'r');

        $i = 0;
        $configStr='';
        $titleStr='';
        $allDataArr = array();

        while(!feof($f)){
            $line = fgets($f);
            $line = self::replace($line);
            if($i == 0){
                $configStr = $line;
            }elseif($i == 1){
                $titleStr = $line;
            }else{
                array_push($allDataArr,$line);
                //$allDataStr = $line;
            }
            $i = $i + 1;
        }

        //配置
        self::setInfoCfg($configStr);

        //表头
        //self::setInfoTitle($titleStr);

        //数据
        self::setInfoData($titleStr,$allDataArr);

    }

    private static function replace($str){
        $reg = array('/\r\n$/','/\n$/');
        $str = preg_replace($reg,'',$str);
        return $str;
    }

    //提取config信息
    private static function setInfoCfg($configStr){
        $finalAll = array(); //键值数组
        $arr = explode(',',$configStr);
        forEach($arr as $val){
            $key = preg_replace('/(.+?):.*/','$1',$val);
            $value = preg_replace('/.+?:(.*)/','$1',$val);

            $finalAll[$key] = $value;

        }

        self::$account = $finalAll['﻿account'];
        self::$password = $finalAll['password'];
        self::$apicode = $finalAll['apicode'];
        self::$login_url = $finalAll['login_url'];
        self::$data_url = $finalAll['data_url'];


    }
    //提取title
    private static function setInfoTitle($titleStr){
        $arr = array();
        $titleArr = split(',',$titleStr);
        self::$headerTitle = $titleArr;
    }

    //提取data
    //@param $title 表头
    //@$allDataAll 所有数据
    private static function setInfoData($title,$allDataArr){
        echo '<h1>$title</h1>';
        echo $title;

        $arr = array();
        if(preg_match('/\r\n$/', $title)){
            $title = preg_replace('/\r\n$/', '', $title);
        }

        //$title = preg_replace('/\r\n/','');

        $titleArr = explode(',',$title);

        $finalArr = array(); //

        //self::$targetList = $titleArr;
        forEach($allDataArr as $k => $v){
            $temp = explode(',',$v);
            $temp2 = array();
            forEach($temp as $i => $subVal){
                $temp2[$titleArr[$i]] = $subVal;
            }
            array_push($finalArr,$temp2);
        }
        self::$targetList = $finalArr;
    }

    public static function map(){
        return array(
            'Flag_accountChange' => 'flag_accountChange',
            'Flag_consumption_c' => 'flag_consumption_c',
            'Flag_consumption' => 'flag_consumption',
            'Flag_specialList' => 'flag_specialList',
            'Flag_specialList_c' => 'flag_specialList_c',
            'Flag_payConsumption' => 'flag_payConsumption',
            'Flag_location' => 'flag_location',
            'Flag_telecomCheck' => 'flag_telecomCheck',
            'Flag_stability_c' => 'flag_stability_c',
            'Flag_applyLoan' => 'flag_applyLoan',
            'Flag_accountChangeMonth' => 'flag_accountChangeMonth',
            'Flag_media_c' => 'flag_media_c',
            'Flag_score' => 'flag_score',
            'Flag_datacust' => 'flag_datacust',
            'Flag_rulespeciallist' => 'flag_rulespeciallist',
            'Flag_ruleapplyloan' => 'flag_ruleapplyloan',
            'Flag_authentication' => 'flag_authentication',


            'Accountchange_regionno' => 'ac_regionno',
            'Accountchange_cardindex' => 'ac_cardindex',
            'Accountchange_m1m3_creditcard_cash' => 'ac_m1m3_credit_cash',
            'Accountchange_m1m3_creditcard_default' => 'ac_m1m3_credit_def',
            'Accountchange_m1m3_creditcard_income' => 'ac_m1m3_credit_in',
            'Accountchange_m1m3_creditcard_outgo' => 'ac_m1m3_credit_out',
            'Accountchange_m1m3_creditcard_status' => 'ac_m1m3_credit_status',
            'Accountchange_m1m3_debitcard_balance' => 'ac_m1m3_debit_balance',
            'Accountchange_m1m3_debitcard_income' => 'ac_m1m3_debit_in',
            'Accountchange_m1m3_debitcard_investment' => 'ac_m1m3_debit_invest',
            'Accountchange_m1m3_creditcard_outgo' => 'ac_m1m3_credit_out',
            'Accountchange_m1m3_debitcard_repay' => 'ac_m1m3_debit_repay',
            'Accountchange_m1m3_debitcard_outgo' => 'ac_m1m3_debit_out',
            'Accountchange_m1m3_loan' => 'ac_m1m3_loan',
            'Accountchange_m4m6_creditcard_cash' => 'ac_m4m6_credit_cash',
            'Accountchange_m4m6_creditcard_default' => 'ac_m4m6_credit_def',
            'Accountchange_m4m6_creditcard_income' => 'ac_m4m6_credit_in',
            'Accountchange_m4m6_creditcard_outgo' => 'ac_m4m6_credit_out',
            'Accountchange_m4m6_creditcard_status' => 'ac_m4m6_credit_status',
            'Accountchange_m4m6_debitcard_balance' => 'ac_m4m6_debit_balance',
            'Accountchange_m4m6_debitcard_income' => 'ac_m4m6_debit_in',
            'Accountchange_m4m6_debitcard_investment' => 'ac_m4m6_debit_invest',
            'Accountchange_m4m6_debitcard_outgo' => 'ac_m4m6_debit_out',
            'Accountchange_m4m6_debitcard_repay' => 'ac_m4m6_debit_repay',
            'Accountchange_m4m6_loan' => 'ac_m4m6_loan',
            'Accountchange_m7m9_creditcard_cash' => 'ac_m7m9_credit_cash',
            'Accountchange_m7m9_creditcard_default' => 'ac_m7m9_credit_def',
            'Accountchange_m7m9_creditcard_income' => 'ac_m7m9_credit_in',
            'Accountchange_m7m9_creditcard_outgo' => 'ac_m7m9_credit_out',
            'Accountchange_m7m9_creditcard_status' => 'ac_m7m9_credit_status',
            'Accountchange_m7m9_debitcard_balance' => 'ac_m7m9_debit_balance',
            'Accountchange_m7m9_debitcard_income' => 'ac_m7m9_debit_in',
            'Accountchange_m7m9_debitcard_investment' => 'ac_m7m9_debit_invest',
            'Accountchange_m7m9_debitcard_outgo' => 'ac_m7m9_debit_out',
            'Accountchange_m7m9_debitcard_repay' => 'ac_m7m9_debit_repay',
            'Accountchange_m7m9_loan' => 'ac_m7m9_loan',
            'Accountchange_m10m12_creditcard_cash' => 'ac_m10m12_credit_cash',
            'Accountchange_m10m12_creditcard_default' => 'ac_m10m12_credit_def',
            'Accountchange_m10m12_creditcard_income' => 'ac_m10m12_credit_in',
            'Accountchange_m10m12_creditcard_outgo' => 'ac_m10m12_credit_out',
            'Accountchange_m10m12_creditcard_status' => 'ac_m10m12_credit_status',
            'Accountchange_m10m12_debitcard_balance' => 'ac_m10m12_debit_balance',
            'Accountchange_m10m12_debitcard_income' => 'ac_m10m12_debit_in',
            'Accountchange_m10m12_debitcard_investment' => 'ac_m10m12_debit_invest',
            'Accountchange_m10m12_debitcard_outgo' => 'ac_m10m12_debit_out',
            'Accountchange_m10m12_debitcard_repay' => 'ac_m10m12_debit_repay',
            'Accountchange_m10m12_loan' => 'ac_m10m12_loan',
            'Accountchange_m13m15_creditcard_cash' => 'ac_m13m15_credit_cash',
            'Accountchange_m13m15_creditcard_default' => 'ac_m13m15_credit_def',
            'Accountchange_m13m15_creditcard_income' => 'ac_m13m15_credit_in',
            'Accountchange_m13m15_creditcard_outgo' => 'ac_m13m15_credit_out',
            'Accountchange_m13m15_creditcard_status' => 'ac_m13m15_credit_status',
            'Accountchange_m13m15_debitcard_balance' => 'ac_m13m15_debit_balance',
            'Accountchange_m13m15_debitcard_income' => 'ac_m13m15_debit_in',
            'Accountchange_m13m15_debitcard_investment' => 'ac_m13m15_debit_invest',
            'Accountchange_m13m15_debitcard_outgo' => 'ac_m13m15_debit_out',
            'Accountchange_m13m15_debitcard_repay' => 'ac_m13m15_debit_repay',
            'Accountchange_m13m15_loan' => 'ac_m13m15_loan',
            'Accountchange_m16m18_creditcard_cash' => 'ac_m16m18_credit_cash',
            'Accountchange_m16m18_creditcard_default' => 'ac_m16m18_credit_def',
            'Accountchange_m16m18_creditcard_income' => 'ac_m16m18_credit_in',
            'Accountchange_m16m18_creditcard_outgo' => 'ac_m16m18_credit_out',
            'Accountchange_m16m18_creditcard_status' => 'ac_m16m18_credit_status',
            'Accountchange_m16m18_debitcard_balance' => 'ac_m16m18_debit_balance',
            'Accountchange_m16m18_debitcard_income' => 'ac_m16m18_debit_in',
            'Accountchange_m16m18_debitcard_investment' => 'ac_m16m18_debit_invest',
            'Accountchange_m16m18_debitcard_outgo' => 'ac_m16m18_debit_out',
            'Accountchange_m16m18_debitcard_repay' => 'ac_m16m18_debit_repay',
            'Accountchange_m16m18_loan' => 'ac_m16m18_loan',

            'AccountchangeMonth_cardindex' => 'acm_card_index',
            'AccountchangeMonth_m1_debitcard_balance' => 'acm_m1_debit_balance',
            'AccountchangeMonth_m1_debitcard_outgo' => 'acm_m1_debit_out',
            'AccountchangeMonth_m1_debitcard_investment' => 'acm_m1_debit_invest',
            'AccountchangeMonth_m1_debitcard_repay' => 'acm_m1_debit_repay',
            'AccountchangeMonth_m1_debitcard_income' => 'acm_m1_debit_in',
            'AccountchangeMonth_m1_creditcard_cash' => 'acm_m1_credit_cash',
            'AccountchangeMonth_m1_creditcard_default' => 'acm_m1_credit_def',
            'AccountchangeMonth_m1_creditcard_income' => 'acm_m1_credit_in',
            'AccountchangeMonth_m1_creditcard_outgo' =>  'acm_m1_credit_out',
            'AccountchangeMonth_m1_loan' => 'acm_m1_loan',
            'AccountchangeMonth_m2_debitcard_balance' => 'acm_m2_debit_balance',
            'AccountchangeMonth_m2_debitcard_outgo' => 'acm_m2_debit_out',
            'AccountchangeMonth_m2_debitcard_investment' => 'acm_m2_debit_invest',
            'AccountchangeMonth_m2_debitcard_repay' => 'acm_m2_debit_repay',
            'AccountchangeMonth_m2_debitcard_income' => 'acm_m2_debit_in',
            'AccountchangeMonth_m2_creditcard_cash' => 'acm_m2_credit_cash',
            'AccountchangeMonth_m2_creditcard_default' => 'acm_m2_credit_def',
            'AccountchangeMonth_m2_creditcard_income' => 'acm_m2_credit_in',
            'AccountchangeMonth_m2_creditcard_outgo' =>  'acm_m2_credit_out',
            'AccountchangeMonth_m2_loan' => 'acm_m2_loan',
            'AccountchangeMonth_m3_debitcard_balance' => 'acm_m3_debit_balance',
            'AccountchangeMonth_m3_debitcard_outgo' => 'acm_m3_debit_out',
            'AccountchangeMonth_m3_debitcard_investment' => 'acm_m3_debit_invest',
            'AccountchangeMonth_m3_debitcard_repay' => 'acm_m3_debit_repay',
            'AccountchangeMonth_m3_debitcard_income' => 'acm_m3_debit_in',
            'AccountchangeMonth_m3_creditcard_cash' => 'acm_m3_credit_cash',
            'AccountchangeMonth_m3_creditcard_default' => 'acm_m3_credit_def',
            'AccountchangeMonth_m3_creditcard_income' => 'acm_m3_credit_in',
            'AccountchangeMonth_m3_creditcard_outgo' =>  'acm_m3_credit_out',
            'AccountchangeMonth_m3_loan' => 'acm_m3_loan',
            'AccountchangeMonth_m4_debitcard_balance' => 'acm_m4_debit_balance',
            'AccountchangeMonth_m4_debitcard_outgo' => 'acm_m4_debit_out',
            'AccountchangeMonth_m4_debitcard_investment' => 'acm_m4_debit_invest',
            'AccountchangeMonth_m4_debitcard_repay' => 'acm_m4_debit_repay',
            'AccountchangeMonth_m4_debitcard_income' => 'acm_m4_debit_in',
            'AccountchangeMonth_m4_creditcard_cash' => 'acm_m4_credit_cash',
            'AccountchangeMonth_m4_creditcard_default' => 'acm_m4_credit_def',
            'AccountchangeMonth_m4_creditcard_income' => 'acm_m4_credit_in',
            'AccountchangeMonth_m4_creditcard_outgo' =>  'acm_m4_credit_out',
            'AccountchangeMonth_m4_loan' => 'acm_m4_loan',
            'AccountchangeMonth_m5_debitcard_balance' => 'acm_m5_debit_balance',
            'AccountchangeMonth_m5_debitcard_outgo' => 'acm_m5_debit_out',
            'AccountchangeMonth_m5_debitcard_investment' => 'acm_m5_debit_invest',
            'AccountchangeMonth_m5_debitcard_repay' => 'acm_m5_debit_repay',
            'AccountchangeMonth_m5_debitcard_income' => 'acm_m5_debit_in',
            'AccountchangeMonth_m5_creditcard_cash' => 'acm_m5_credit_cash',
            'AccountchangeMonth_m5_creditcard_default' => 'acm_m5_credit_def',
            'AccountchangeMonth_m5_creditcard_income' => 'acm_m5_credit_in',
            'AccountchangeMonth_m5_creditcard_outgo' =>  'acm_m5_credit_out',
            'AccountchangeMonth_m5_loan' => 'acm_m5_loan',
            'AccountchangeMonth_m6_debitcard_balance' => 'acm_m6_debit_balance',
            'AccountchangeMonth_m6_debitcard_outgo' => 'acm_m6_debit_out',
            'AccountchangeMonth_m6_debitcard_investment' => 'acm_m6_debit_invest',
            'AccountchangeMonth_m6_debitcard_repay' => 'acm_m6_debit_repay',
            'AccountchangeMonth_m6_debitcard_income' => 'acm_m6_debit_in',
            'AccountchangeMonth_m6_creditcard_cash' => 'acm_m6_credit_cash',
            'AccountchangeMonth_m6_creditcard_default' => 'acm_m6_credit_def',
            'AccountchangeMonth_m6_creditcard_income' => 'acm_m6_credit_in',
            'AccountchangeMonth_m6_creditcard_outgo' =>  'acm_m6_credit_out',
            'AccountchangeMonth_m6_loan' => 'acm_m6_loan',
            'AccountchangeMonth_m7m9_debitcard_balance' => 'acm_m7m9_debit_balance',
            'AccountchangeMonth_m7m9_debitcard_outgo' => 'acm_m7m9_debit_out',
            'AccountchangeMonth_m7m9_debitcard_investment' => 'acm_m7m9_debit_invest',
            'AccountchangeMonth_m7m9_debitcard_repay' => 'acm_m7m9_debit_repay',
            'AccountchangeMonth_m7m9_debitcard_income' => 'acm_m7m9_debit_in',
            'AccountchangeMonth_m7m9_creditcard_cash' => 'acm_m7m9_credit_cash',
            'AccountchangeMonth_m7m9_creditcard_default' => 'acm_m7m9_credit_def',
            'AccountchangeMonth_m7m9_creditcard_income' => 'acm_m7m9_credit_in',
            'AccountchangeMonth_m7m9_creditcard_outgo' =>  'acm_m7m9_credit_out',
            'AccountchangeMonth_m7m9_loan' => 'acm_m7m9_loan',
            'AccountchangeMonth_m10m12_debitcard_balance' => 'acm_m10m12_debit_balance',
            'AccountchangeMonth_m10m12_debitcard_outgo' => 'acm_m10m12_debit_out',
            'AccountchangeMonth_m10m12_debitcard_investment' => 'acm_m10m12_debit_invest',
            'AccountchangeMonth_m10m12_debitcard_repay' => 'acm_m10m12_debit_repay',
            'AccountchangeMonth_m10m12_debitcard_income' => 'acm_m10m12_debit_in',
            'AccountchangeMonth_m10m12_creditcard_cash' => 'acm_m10m12_credit_cash',
            'AccountchangeMonth_m10m12_creditcard_default' => 'acm_m10m12_credit_def',
            'AccountchangeMonth_m10m12_creditcard_income' => 'acm_m10m12_credit_in',
            'AccountchangeMonth_m10m12_creditcard_outgo' =>  'acm_m10m12_credit_out',
            'AccountchangeMonth_m10m12_loan' => 'acm_m10m12_loan',
            'AccountchangeMonth_m13m15_debitcard_balance' => 'acm_m13m15_debit_balance',
            'AccountchangeMonth_m13m15_debitcard_outgo' => 'acm_m13m15_debit_out',
            'AccountchangeMonth_m13m15_debitcard_investment' => 'acm_m13m15_debit_invest',
            'AccountchangeMonth_m13m15_debitcard_repay' => 'acm_m13m15_debit_repay',
            'AccountchangeMonth_m13m15_debitcard_income' => 'acm_m13m15_debit_in',
            'AccountchangeMonth_m13m15_creditcard_cash' => 'acm_m13m15_credit_cash',
            'AccountchangeMonth_m13m15_creditcard_default' => 'acm_m13m15_credit_def',
            'AccountchangeMonth_m13m15_creditcard_income' => 'acm_m13m15_credit_in',
            'AccountchangeMonth_m13m15_creditcard_outgo' =>  'acm_m13m15_credit_out',
            'AccountchangeMonth_m13m15_loan' => 'acm_m13m15_loan',
            'AccountchangeMonth_m16m18_debitcard_balance' => 'acm_m16m18_debit_balance',
            'AccountchangeMonth_m16m18_debitcard_outgo' => 'acm_m16m18_debit_out',
            'AccountchangeMonth_m16m18_debitcard_investment' => 'acm_m16m18_debit_invest',
            'AccountchangeMonth_m16m18_debitcard_repay' => 'acm_m16m18_debit_repay',
            'AccountchangeMonth_m16m18_debitcard_income' => 'acm_m16m18_debit_in',
            'AccountchangeMonth_m16m18_creditcard_cash' => 'acm_m16m18_credit_cash',
            'AccountchangeMonth_m16m18_creditcard_default' => 'acm_m16m18_credit_def',
            'AccountchangeMonth_m16m18_creditcard_income' => 'acm_m16m18_credit_in',
            'AccountchangeMonth_m16m18_creditcard_outgo' =>  'acm_m16m18_credit_out',
            'AccountchangeMonth_m16m18_loan' => 'acm_m16m18_loan',

            'ApplyLoan_month3_cell_bank_selfnumber' => 'al_m3_cell_bank_selfnum',
            'ApplyLoan_month3_id_bank_selfnumber' => 'al_m3_id_bank_selfnum',
            'ApplyLoan_month3_gid_bank_selfnumber' => 'al_m3_gid_bank_selfnum',
            'ApplyLoan_month3_id_bank_allnumber' => 'al_m3_id_bank_allnum',
            'ApplyLoan_month3_cell_bank_allnumber' => 'al_m3_cell_bank_allnum',
            'ApplyLoan_month3_gid_bank_allnumber' => 'al_m3_gid_bank_allnum',
            'ApplyLoan_month3_gid_bank_orgnumber' => 'al_m3_gid_bank_orgnum',
            'ApplyLoan_month3_cell_bank_orgnumber' => 'al_m3_cell_bank_orgnum',
            'ApplyLoan_month3_id_bank_orgnumber' => 'al_m3_id_bank_orgnum',
            'ApplyLoan_month6_cell_bank_selfnumber' => 'al_m6_cell_bank_selfnum',
            'ApplyLoan_month6_id_bank_selfnumber' => 'al_m6_id_bank_selfnum',
            'ApplyLoan_month6_gid_bank_selfnumber' => 'al_m6_gid_bank_selfnum',
            'ApplyLoan_month6_id_bank_allnumber' => 'al_m6_id_bank_allnum',
            'ApplyLoan_month6_cell_bank_allnumber' => 'al_m6_cell_bank_allnum',
            'ApplyLoan_month6_gid_bank_allnumber' => 'al_m6_gid_bank_allnum',
            'ApplyLoan_month6_gid_bank_orgnumber' => 'al_m6_gid_bank_orgnum',
            'ApplyLoan_month6_cell_bank_orgnumber' => 'al_m6_cell_bank_orgnum',
            'ApplyLoan_month6_id_bank_orgnumber' => 'al_m6_id_bank_orgnum',
            'ApplyLoan_month12_cell_bank_selfnumber' => 'al_m12_cell_bank_selfnum',
            'ApplyLoan_month12_id_bank_selfnumber' => 'al_m12_id_bank_selfnum',
            'ApplyLoan_month12_gid_bank_selfnumber' => 'al_m12_gid_bank_selfnum',
            'ApplyLoan_month12_id_bank_allnumber' => 'al_m12_id_bank_allnum',
            'ApplyLoan_month12_cell_bank_allnumber' => 'al_m12_cell_bank_allnum',
            'ApplyLoan_month12_gid_bank_allnumber' => 'al_m12_gid_bank_allnum',
            'ApplyLoan_month12_gid_bank_orgnumber' => 'al_m12_gid_bank_orgnum',
            'ApplyLoan_month12_cell_bank_orgnumber' => 'al_m12_cell_bank_orgnum',
            'ApplyLoan_month12_id_bank_orgnumber' => 'al_m12_id_bank_orgnum',
            'ApplyLoan_month3_cell_notbank_selfnumber' => 'al_m3_cell_notbank_selfnum',
            'ApplyLoan_month3_id_notbank_selfnumber' => 'al_m3_id_notbank_selfnum',
            'ApplyLoan_month3_gid_notbank_selfnumber' => 'al_m3_gid_notbank_selfnum',
            'ApplyLoan_month3_id_notbank_allnumber' => 'al_m3_id_notbank_allnum',
            'ApplyLoan_month3_cell_notbank_allnumber' => 'al_m3_cell_notbank_allnum',
            'ApplyLoan_month3_gid_notbank_allnumber' => 'al_m3_gid_notbank_allnum',
            'ApplyLoan_month3_gid_notbank_orgnumber' => 'al_m3_gid_notbank_orgnum',
            'ApplyLoan_month3_cell_notbank_orgnumber' => 'al_m3_cell_notbank_orgnum',
            'ApplyLoan_month3_id_notbank_orgnumber' => 'al_m3_id_notbank_orgnum',
            'ApplyLoan_month6_cell_notbank_selfnumber' => 'al_m6_cell_notbank_selfnum',
            'ApplyLoan_month6_id_notbank_selfnumber' => 'al_m6_id_notbank_selfnum',
            'ApplyLoan_month6_gid_notbank_selfnumber' => 'al_m6_gid_notbank_selfnum',
            'ApplyLoan_month6_id_notbank_allnumber' => 'al_m6_id_notbank_allnum',
            'ApplyLoan_month6_cell_notbank_allnumber' => 'al_m6_cell_notbank_allnum',
            'ApplyLoan_month6_gid_notbank_allnumber' => 'al_m6_gid_notbank_allnum',
            'ApplyLoan_month6_gid_notbank_orgnumber' => 'al_m6_gid_notbank_orgnum',
            'ApplyLoan_month6_cell_notbank_orgnumber' => 'al_m6_cell_notbank_orgnum',
            'ApplyLoan_month6_id_notbank_orgnumber' => 'al_m6_id_notbank_orgnum',
            'ApplyLoan_month12_cell_notbank_selfnumber' => 'al_m12_cell_notbank_selfnum',
            'ApplyLoan_month12_id_notbank_selfnumber' => 'al_m12_id_notbank_selfnum',
            'ApplyLoan_month12_gid_notbank_selfnumber' => 'al_m12_gid_notbank_selfnum',
            'ApplyLoan_month12_id_notbank_allnumber' => 'al_m12_id_notbank_allnum',
            'ApplyLoan_month12_cell_notbank_allnumber' => 'al_m12_cell_notbank_allnum',
            'ApplyLoan_month12_gid_notbank_allnumber' => 'al_m12_gid_notbank_allnum',
            'ApplyLoan_month12_gid_notbank_orgnumber' => 'al_m12_gid_notbank_orgnum',
            'ApplyLoan_month12_cell_notbank_orgnumber' => 'al_m12_cell_notbank_orgnum',
            'ApplyLoan_month12_id_notbank_orgnumber' => 'al_m12_id_notbank_orgnum',
            'Assets_house' => 'assets_house',
            'Assets_car' => 'assets_car',
            'Assets_fin' => 'assets_fin',
            'Assets_wealth' => 'assets_wealth',
            'Authentication_id' => 'auth_id',
            'Authentication_cell' => 'auth_cell',
            'Authentication_mail' => 'auth_mail',
            'Authentication_key_relation' => 'auth_key_relation',
            'Authentication_tel_home' => 'auth_tel_home',
            'Authentication_tel_biz' => 'auth_tel_biz',
            'Authentication_name' => 'auth_name',
            'Brand_top1' => 'brand_top1',
            'Brand_top2' => 'brand_top2',
            'Brand_top3' => 'brand_top3',
            'Brand_top4' => 'brand_top4',
            'Brand_top5' => 'brand_top5',
            'Consumption_month3_其他_pay' => 'cons_m3_QT_pay',
            'Consumption_month3_服装配饰_pay' => 'cons_m3_FZPS_pay',
            'Consumption_month3_鞋_pay' => 'cons_m3_X_pay',
            'Consumption_month3_母婴用品_pay' => 'cons_m3_MYYP_pay',
            'Consumption_month3_文化娱乐_pay' => 'cons_m3_WHYL_pay',
            'Consumption_month3_运动户外_pay' => 'cons_m3_YDHW_pay',
            'Consumption_month3_日用百货_pay' => 'cons_m3_RYBH_pay',
            'Consumption_month3_个护化妆_pay' => 'cons_m3_GHHZ_pay',
            'Consumption_month3_箱包_pay' => 'cons_m3_XB_pay',
            'Consumption_month3_手机/手机配件_pay' => 'cons_m3_SJSJPJ_pay',
            'Consumption_month3_电脑/办公_pay' => 'cons_m3_DNBG_pay',
            'Consumption_month3_美食特产_pay' => 'cons_m3_MSTC_pay',
            'Consumption_month3_家具建材_pay' => 'cons_m3_JJJC_pay',
            'Consumption_month3_通讯_pay' => 'cons_m3_TX_pay',
            'Consumption_month3_家用电器_pay' => 'cons_m3_JYDQ_pay',
            'Consumption_month3_家居家纺_pay' => 'cons_m3_JJJF_pay',
            'Consumption_month3_数码_pay' => 'cons_m3_SM_pay',
            'Consumption_month3_钟表首饰_pay' => 'cons_m3_ZBPS_pay',
            'Consumption_month3_汽车用品_pay' => 'cons_m3_QZPS_pay',
            'Consumption_month3_网络游戏/虚拟物品_pay' => 'cons_m3_WLYLXNYX_pay',
            'Consumption_month3_医疗保健_pay' => 'cons_m3_YLBJ_pay',
            'Consumption_month3_本地生活_pay' => 'cons_m3_BDSH_pay',
            'Consumption_month3_珠宝贵金属_pay' => 'cons_m3_ZBGJS_pay',
            'Consumption_month3_收藏_pay' => 'cons_m3_SC_pay',
            'Consumption_month3_宠物生活_pay' => 'cons_m3_CWSH_pay',
            'Consumption_month3_出差旅游_pay' => 'cons_m3_CCLY_pay',
            'Consumption_month3_教育培训_pay' => 'cons_m3_JYPX_pay',
            'Consumption_month3_房产_pay' => 'cons_m3_FC_pay',
            'Consumption_month3_保险/理财_pay' => 'cons_m3_BXLC_pay',
            'Consumption_month3_其他_number' => 'cons_m3_QT_num',
            'Consumption_month3_服装配饰_number' => 'cons_m3_FZPS_num',
            'Consumption_month3_鞋_number' => 'cons_m3_X_num',
            'Consumption_month3_母婴用品_number' => 'cons_m3_MYYP_num',
            'Consumption_month3_文化娱乐_number' => 'cons_m3_WHYL_num',
            'Consumption_month3_运动户外_number' => 'cons_m3_YDHW_num',
            'Consumption_month3_日用百货_number' => 'cons_m3_RYBH_num',
            'Consumption_month3_个护化妆_number' => 'cons_m3_GHHZ_num',
            'Consumption_month3_箱包_number' => 'cons_m3_XB_num',
            'Consumption_month3_手机/手机配件_number' => 'cons_m3_SJSJPJ_num',
            'Consumption_month3_电脑/办公_number' => 'cons_m3_DNBG_num',
            'Consumption_month3_美食特产_number' => 'cons_m3_MSTC_num',
            'Consumption_month3_家具建材_number' => 'cons_m3_JJJC_num',
            'Consumption_month3_通讯_number' => 'cons_m3_TX_num',
            'Consumption_month3_家用电器_number' => 'cons_m3_JYDQ_num',
            'Consumption_month3_家居家纺_number' => 'cons_m3_JJJF_num',
            'Consumption_month3_数码_number' => 'cons_m3_SM_num',
            'Consumption_month3_钟表首饰_number' => 'cons_m3_ZBPS_num',
            'Consumption_month3_汽车用品_number' => 'cons_m3_QZPS_num',
            'Consumption_month3_网络游戏/虚拟物品_number' => 'cons_m3_WLYLXNYX_num',
            'Consumption_month3_医疗保健_number' => 'cons_m3_YLBJ_num',
            'Consumption_month3_本地生活_number' => 'cons_m3_BDSH_num',
            'Consumption_month3_珠宝贵金属_number' => 'cons_m3_ZBGJS_num',
            'Consumption_month3_收藏_number' => 'cons_m3_SC_num',
            'Consumption_month3_宠物生活_number' => 'cons_m3_CWSH_num',
            'Consumption_month3_出差旅游_number' => 'cons_m3_CCLY_num',
            'Consumption_month3_教育培训_number' => 'cons_m3_JYPX_num',
            'Consumption_month3_房产_number' => 'cons_m3_FC_num',
            'Consumption_month3_保险/理财_number' => 'cons_m3_BXLC_num',
            'Consumption_month3_其他_visits' => 'cons_m3_QT_visits',
            'Consumption_month3_服装配饰_visits' => 'cons_m3_FZPS_visits',
            'Consumption_month3_鞋_visits' => 'cons_m3_X_visits',
            'Consumption_month3_母婴用品_visits' => 'cons_m3_MYYP_visits',
            'Consumption_month3_文化娱乐_visits' => 'cons_m3_WHYL_visits',
            'Consumption_month3_运动户外_visits' => 'cons_m3_YDHW_visits',
            'Consumption_month3_日用百货_visits' => 'cons_m3_RYBH_visits',
            'Consumption_month3_个护化妆_visits' => 'cons_m3_GHHZ_visits',
            'Consumption_month3_箱包_visits' => 'cons_m3_XB_visits',
            'Consumption_month3_手机/手机配件_visits' => 'cons_m3_SJSJPJ_visits',
            'Consumption_month3_电脑/办公_visits' => 'cons_m3_DNBG_visits',
            'Consumption_month3_美食特产_visits' => 'cons_m3_MSTC_visits',
            'Consumption_month3_家具建材_visits' => 'cons_m3_JJJC_visits',
            'Consumption_month3_通讯_visits' => 'cons_m3_TX_visits',
            'Consumption_month3_家用电器_visits' => 'cons_m3_JYDQ_visits',
            'Consumption_month3_家居家纺_visits' => 'cons_m3_JJJF_visits',
            'Consumption_month3_数码_visits' => 'cons_m3_SM_visits',
            'Consumption_month3_钟表首饰_visits' => 'cons_m3_ZBPS_visits',
            'Consumption_month3_汽车用品_visits' => 'cons_m3_QZPS_visits',
            'Consumption_month3_网络游戏/虚拟物品_visits' => 'cons_m3_WLYLXNYX_visits',
            'Consumption_month3_医疗保健_visits' => 'cons_m3_YLBJ_visits',
            'Consumption_month3_本地生活_visits' => 'cons_m3_BDSH_visits',
            'Consumption_month3_珠宝贵金属_visits' => 'cons_m3_ZBGJS_visits',
            'Consumption_month3_收藏_visits' => 'cons_m3_SC_visits',
            'Consumption_month3_宠物生活_visits' => 'cons_m3_CWSH_visits',
            'Consumption_month3_出差旅游_visits' => 'cons_m3_CCLY_visits',
            'Consumption_month3_教育培训_visits' => 'cons_m3_JYPX_visits',
            'Consumption_month3_房产_visits' => 'cons_m3_FC_visits',
            'Consumption_month3_保险/理财_visits' => 'cons_m3_BXLC_visits',
            'Consumption_month6_其他_pay' => 'cons_m6_QT_pay',
            'Consumption_month6_服装配饰_pay' => 'cons_m6_FZPS_pay',
            'Consumption_month6_鞋_pay' => 'cons_m6_X_pay',
            'Consumption_month6_母婴用品_pay' => 'cons_m6_MYYP_pay',
            'Consumption_month6_文化娱乐_pay' => 'cons_m6_WHYL_pay',
            'Consumption_month6_运动户外_pay' => 'cons_m6_YDHW_pay',
            'Consumption_month6_日用百货_pay' => 'cons_m6_RYBH_pay',
            'Consumption_month6_个护化妆_pay' => 'cons_m6_GHHZ_pay',
            'Consumption_month6_箱包_pay' => 'cons_m6_XB_pay',
            'Consumption_month6_手机/手机配件_pay' => 'cons_m6_SJSJPJ_pay',
            'Consumption_month6_电脑/办公_pay' => 'cons_m6_DNBG_pay',
            'Consumption_month6_美食特产_pay' => 'cons_m6_MSTC_pay',
            'Consumption_month6_家具建材_pay' => 'cons_m6_JJJC_pay',
            'Consumption_month6_通讯_pay' => 'cons_m6_TX_pay',
            'Consumption_month6_家用电器_pay' => 'cons_m6_JYDQ_pay',
            'Consumption_month6_家居家纺_pay' => 'cons_m6_JJJF_pay',
            'Consumption_month6_数码_pay' => 'cons_m6_SM_pay',
            'Consumption_month6_钟表首饰_pay' => 'cons_m6_ZBPS_pay',
            'Consumption_month6_汽车用品_pay' => 'cons_m6_QZPS_pay',
            'Consumption_month6_网络游戏/虚拟物品_pay' => 'cons_m6_WLYLXNYX_pay',
            'Consumption_month6_医疗保健_pay' => 'cons_m6_YLBJ_pay',
            'Consumption_month6_本地生活_pay' => 'cons_m6_BDSH_pay',
            'Consumption_month6_珠宝贵金属_pay' => 'cons_m6_ZBGJS_pay',
            'Consumption_month6_收藏_pay' => 'cons_m6_SC_pay',
            'Consumption_month6_宠物生活_pay' => 'cons_m6_CWSH_pay',
            'Consumption_month6_出差旅游_pay' => 'cons_m6_CCLY_pay',
            'Consumption_month6_教育培训_pay' => 'cons_m6_JYPX_pay',
            'Consumption_month6_房产_pay' => 'cons_m6_FC_pay',
            'Consumption_month6_保险/理财_pay' => 'cons_m6_BXLC_pay',
            'Consumption_month6_其他_number' => 'cons_m6_QT_num',
            'Consumption_month6_服装配饰_number' => 'cons_m6_FZPS_num',
            'Consumption_month6_鞋_number' => 'cons_m6_X_num',
            'Consumption_month6_母婴用品_number' => 'cons_m6_MYYP_num',
            'Consumption_month6_文化娱乐_number' => 'cons_m6_WHYL_num',
            'Consumption_month6_运动户外_number' => 'cons_m6_YDHW_num',
            'Consumption_month6_日用百货_number' => 'cons_m6_RYBH_num',
            'Consumption_month6_个护化妆_number' => 'cons_m6_GHHZ_num',
            'Consumption_month6_箱包_number' => 'cons_m6_XB_num',
            'Consumption_month6_手机/手机配件_number' => 'cons_m6_SJSJPJ_num',
            'Consumption_month6_电脑/办公_number' => 'cons_m6_DNBG_num',
            'Consumption_month6_美食特产_number' => 'cons_m6_MSTC_num',
            'Consumption_month6_家具建材_number' => 'cons_m6_JJJC_num',
            'Consumption_month6_通讯_number' => 'cons_m6_TX_num',
            'Consumption_month6_家用电器_number' => 'cons_m6_JYDQ_num',
            'Consumption_month6_家居家纺_number' => 'cons_m6_JJJF_num',
            'Consumption_month6_数码_number' => 'cons_m6_SM_num',
            'Consumption_month6_钟表首饰_number' => 'cons_m6_ZBPS_num',
            'Consumption_month6_汽车用品_number' => 'cons_m6_QZPS_num',
            'Consumption_month6_网络游戏/虚拟物品_number' => 'cons_m6_WLYLXNYX_num',
            'Consumption_month6_医疗保健_number' => 'cons_m6_YLBJ_num',
            'Consumption_month6_本地生活_number' => 'cons_m6_BDSH_num',
            'Consumption_month6_珠宝贵金属_number' => 'cons_m6_ZBGJS_num',
            'Consumption_month6_收藏_number' => 'cons_m6_SC_num',
            'Consumption_month6_宠物生活_number' => 'cons_m6_CWSH_num',
            'Consumption_month6_出差旅游_number' => 'cons_m6_CCLY_num',
            'Consumption_month6_教育培训_number' => 'cons_m6_JYPX_num',
            'Consumption_month6_房产_number' => 'cons_m6_FC_num',
            'Consumption_month6_保险/理财_number' => 'cons_m6_BXLC_num',
            'Consumption_month6_其他_visits' => 'cons_m6_QT_visits',
            'Consumption_month6_服装配饰_visits' => 'cons_m6_FZPS_visits',
            'Consumption_month6_鞋_visits' => 'cons_m6_X_visits',
            'Consumption_month6_母婴用品_visits' => 'cons_m6_MYYP_visits',
            'Consumption_month6_文化娱乐_visits' => 'cons_m6_WHYL_visits',
            'Consumption_month6_运动户外_visits' => 'cons_m6_YDHW_visits',
            'Consumption_month6_日用百货_visits' => 'cons_m6_RYBH_visits',
            'Consumption_month6_个护化妆_visits' => 'cons_m6_GHHZ_visits',
            'Consumption_month6_箱包_visits' => 'cons_m6_XB_visits',
            'Consumption_month6_手机/手机配件_visits' => 'cons_m6_SJSJPJ_visits',
            'Consumption_month6_电脑/办公_visits' => 'cons_m6_DNBG_visits',
            'Consumption_month6_美食特产_visits' => 'cons_m6_MSTC_visits',
            'Consumption_month6_家具建材_visits' => 'cons_m6_JJJC_visits',
            'Consumption_month6_通讯_visits' => 'cons_m6_TX_visits',
            'Consumption_month6_家用电器_visits' => 'cons_m6_JYDQ_visits',
            'Consumption_month6_家居家纺_visits' => 'cons_m6_JJJF_visits',
            'Consumption_month6_数码_visits' => 'cons_m6_SM_visits',
            'Consumption_month6_钟表首饰_visits' => 'cons_m6_ZBPS_visits',
            'Consumption_month6_汽车用品_visits' => 'cons_m6_QZPS_visits',
            'Consumption_month6_网络游戏/虚拟物品_visits' => 'cons_m6_WLYLXNYX_visits',
            'Consumption_month6_医疗保健_visits' => 'cons_m6_YLBJ_visits',
            'Consumption_month6_本地生活_visits' => 'cons_m6_BDSH_visits',
            'Consumption_month6_珠宝贵金属_visits' => 'cons_m6_ZBGJS_visits',
            'Consumption_month6_收藏_visits' => 'cons_m6_SC_visits',
            'Consumption_month6_宠物生活_visits' => 'cons_m6_CWSH_visits',
            'Consumption_month6_出差旅游_visits' => 'cons_m6_CCLY_visits',
            'Consumption_month6_教育培训_visits' => 'cons_m6_JYPX_visits',
            'Consumption_month6_房产_visits' => 'cons_m6_FC_visits',
            'Consumption_month6_保险/理财_visits' => 'cons_m6_BXLC_visits',
            'Consumption_month12_其他_pay' => 'cons_m12_QT_pay',
            'Consumption_month12_服装配饰_pay' => 'cons_m12_FZPS_pay',
            'Consumption_month12_鞋_pay' => 'cons_m12_X_pay',
            'Consumption_month12_母婴用品_pay' => 'cons_m12_MYYP_pay',
            'Consumption_month12_文化娱乐_pay' => 'cons_m12_WHYL_pay',
            'Consumption_month12_运动户外_pay' => 'cons_m12_YDHW_pay',
            'Consumption_month12_日用百货_pay' => 'cons_m12_RYBH_pay',
            'Consumption_month12_个护化妆_pay' => 'cons_m12_GHHZ_pay',
            'Consumption_month12_箱包_pay' => 'cons_m12_XB_pay',
            'Consumption_month12_手机/手机配件_pay' => 'cons_m12_SJSJPJ_pay',
            'Consumption_month12_电脑/办公_pay' => 'cons_m12_DNBG_pay',
            'Consumption_month12_美食特产_pay' => 'cons_m12_MSTC_pay',
            'Consumption_month12_家具建材_pay' => 'cons_m12_JJJC_pay',
            'Consumption_month12_通讯_pay' => 'cons_m12_TX_pay',
            'Consumption_month12_家用电器_pay' => 'cons_m12_JYDQ_pay',
            'Consumption_month12_家居家纺_pay' => 'cons_m12_JJJF_pay',
            'Consumption_month12_数码_pay' => 'cons_m12_SM_pay',
            'Consumption_month12_钟表首饰_pay' => 'cons_m12_ZBPS_pay',
            'Consumption_month12_汽车用品_pay' => 'cons_m12_QZPS_pay',
            'Consumption_month12_网络游戏/虚拟物品_pay' => 'cons_m12_WLYLXNYX_pay',
            'Consumption_month12_医疗保健_pay' => 'cons_m12_YLBJ_pay',
            'Consumption_month12_本地生活_pay' => 'cons_m12_BDSH_pay',
            'Consumption_month12_珠宝贵金属_pay' => 'cons_m12_ZBGJS_pay',
            'Consumption_month12_收藏_pay' => 'cons_m12_SC_pay',
            'Consumption_month12_宠物生活_pay' => 'cons_m12_CWSH_pay',
            'Consumption_month12_出差旅游_pay' => 'cons_m12_CCLY_pay',
            'Consumption_month12_教育培训_pay' => 'cons_m12_JYPX_pay',
            'Consumption_month12_房产_pay' => 'cons_m12_FC_pay',
            'Consumption_month12_保险/理财_pay' => 'cons_m12_BXLC_pay',
            'Consumption_month12_其他_number' => 'cons_m12_QT_num',
            'Consumption_month12_服装配饰_number' => 'cons_m12_FZPS_num',
            'Consumption_month12_鞋_number' => 'cons_m12_X_num',
            'Consumption_month12_母婴用品_number' => 'cons_m12_MYYP_num',
            'Consumption_month12_文化娱乐_number' => 'cons_m12_WHYL_num',
            'Consumption_month12_运动户外_number' => 'cons_m12_YDHW_num',
            'Consumption_month12_日用百货_number' => 'cons_m12_RYBH_num',
            'Consumption_month12_个护化妆_number' => 'cons_m12_GHHZ_num',
            'Consumption_month12_箱包_number' => 'cons_m12_XB_num',
            'Consumption_month12_手机/手机配件_number' => 'cons_m12_SJSJPJ_num',
            'Consumption_month12_电脑/办公_number' => 'cons_m12_DNBG_num',
            'Consumption_month12_美食特产_number' => 'cons_m12_MSTC_num',
            'Consumption_month12_家具建材_number' => 'cons_m12_JJJC_num',
            'Consumption_month12_通讯_number' => 'cons_m12_TX_num',
            'Consumption_month12_家用电器_number' => 'cons_m12_JYDQ_num',
            'Consumption_month12_家居家纺_number' => 'cons_m12_JJJF_num',
            'Consumption_month12_数码_number' => 'cons_m12_SM_num',
            'Consumption_month12_钟表首饰_number' => 'cons_m12_ZBPS_num',
            'Consumption_month12_汽车用品_number' => 'cons_m12_QZPS_num',
            'Consumption_month12_网络游戏/虚拟物品_number' => 'cons_m12_WLYLXNYX_num',
            'Consumption_month12_医疗保健_number' => 'cons_m12_YLBJ_num',
            'Consumption_month12_本地生活_number' => 'cons_m12_BDSH_num',
            'Consumption_month12_珠宝贵金属_number' => 'cons_m12_ZBGJS_num',
            'Consumption_month12_收藏_number' => 'cons_m12_SC_num',
            'Consumption_month12_宠物生活_number' => 'cons_m12_CWSH_num',
            'Consumption_month12_出差旅游_number' => 'cons_m12_CCLY_num',
            'Consumption_month12_教育培训_number' => 'cons_m12_JYPX_num',
            'Consumption_month12_房产_number' => 'cons_m12_FC_number',
            'Consumption_month12_保险/理财_number' => 'cons_m12_BXLC_num',
            'Consumption_month12_其他_visits' => 'cons_m12_QT_visits',
            'Consumption_month12_服装配饰_visits' => 'cons_m12_FZPS_visits',
            'Consumption_month12_鞋_visits' => 'cons_m12_X_visits',
            'Consumption_month12_母婴用品_visits' => 'cons_m12_MYYP_visits',
            'Consumption_month12_文化娱乐_visits' => 'cons_m12_WHYL_visits',
            'Consumption_month12_运动户外_visits' => 'cons_m12_YDHW_visits',
            'Consumption_month12_日用百货_visits' => 'cons_m12_RYBH_visits',
            'Consumption_month12_个护化妆_visits' => 'cons_m12_GHHZ_visits',
            'Consumption_month12_箱包_visits' => 'cons_m12_XB_visits',
            'Consumption_month12_手机/手机配件_visits' => 'cons_m12_SJSJPJ_visits',
            'Consumption_month12_电脑/办公_visits' => 'cons_m12_DNBG_visits',
            'Consumption_month12_美食特产_visits' => 'cons_m12_MSTC_visits',
            'Consumption_month12_家具建材_visits' => 'cons_m12_JJJC_visits',
            'Consumption_month12_通讯_visits' => 'cons_m12_TX_visits',
            'Consumption_month12_家用电器_visits' => 'cons_m12_JYDQ_visits',
            'Consumption_month12_家居家纺_visits' => 'cons_m12_JJJF_visits',
            'Consumption_month12_数码_visits' => 'cons_m12_SM_visits',
            'Consumption_month12_钟表首饰_visits' => 'cons_m12_ZBPS_visits',
            'Consumption_month12_汽车用品_visits' => 'cons_m12_QZPS_visits',
            'Consumption_month12_网络游戏/虚拟物品_visits' => 'cons_m12_WLYLXNYX_visits',
            'Consumption_month12_医疗保健_visits' => 'cons_m12_YLBJ_visits',
            'Consumption_month12_本地生活_visits' => 'cons_m12_BDSH_visits',
            'Consumption_month12_珠宝贵金属_visits' => 'cons_m12_ZBGJS_visits',
            'Consumption_month12_收藏_visits' => 'cons_m12_SC_visits',
            'Consumption_month12_宠物生活_visits' => 'cons_m12_CWSH_visits',
            'Consumption_month12_出差旅游_visits' => 'cons_m12_CCLY_visits',
            'Consumption_month12_教育培训_visits' => 'cons_m12_JYPX_visits',
            'Consumption_month12_房产_visits' => 'cons_m12_FC_visits',
            'Consumption_month12_保险/理财_visits' => 'cons_m12_BXLC_visits',
            'Consumption_month12_其他_maxpay' => 'cons_m12_QT_maxpay',
            'Consumption_month12_服装配饰_maxpay' => 'cons_m12_FZPS_maxpay',
            'Consumption_month12_鞋_maxpay' => 'cons_m12_X_maxpay',
            'Consumption_month12_母婴用品_maxpay' => 'cons_m12_MYYP_maxpay',
            'Consumption_month12_文化娱乐_maxpay' => 'cons_m12_WHYL_maxpay',
            'Consumption_month12_运动户外_maxpay' => 'cons_m12_YDHW_maxpay',
            'Consumption_month12_日用百货_maxpay' => 'cons_m12_RYBH_maxpay',
            'Consumption_month12_个护化妆_maxpay' => 'cons_m12_GHHZ_maxpay',
            'Consumption_month12_箱包_maxpay' => 'cons_m12_XB_maxpay',
            'Consumption_month12_手机/手机配件_maxpay' => 'cons_m12_SJSJPJ_maxpay',
            'Consumption_month12_电脑/办公_maxpay' => 'cons_m12_DNBG_maxpay',
            'Consumption_month12_美食特产_maxpay' => 'cons_m12_MSTC_maxpay',
            'Consumption_month12_家具建材_maxpay' => 'cons_m12_JJJC_maxpay',
            'Consumption_month12_通讯_maxpay' => 'cons_m12_TX_maxpay',
            'Consumption_month12_家用电器_maxpay' => 'cons_m12_JYDQ_maxpay',
            'Consumption_month12_家居家纺_maxpay' => 'cons_m12_JJJF_maxpay',
            'Consumption_month12_数码_maxpay' => 'cons_m12_SM_maxpay',
            'Consumption_month12_钟表首饰_maxpay' => 'cons_m12_ZBPS_maxpay',
            'Consumption_month12_汽车用品_maxpay' => 'cons_m12_QZPS_maxpay',
            'Consumption_month12_网络游戏/虚拟物品_maxpay' => 'cons_m12_WLYLXNYX_maxpay',
            'Consumption_month12_医疗保健_maxpay' => 'cons_m12_YLBJ_maxpay',
            'Consumption_month12_本地生活_maxpay' => 'cons_m12_BDSH_maxpay',
            'Consumption_month12_珠宝贵金属_maxpay' => 'cons_m12_ZBGJS_maxpay',
            'Consumption_month12_收藏_maxpay' => 'cons_m12_SC_maxpay',
            'Consumption_month12_宠物生活_maxpay' => 'cons_m12_CWSH_maxpay',
            'Consumption_month12_出差旅游_maxpay' => 'cons_m12_CCLY_maxpay',
            'Consumption_month12_教育培训_maxpay' => 'cons_m12_JYPX_maxpay',
            'Consumption_month12_房产_maxpay' => 'cons_m12_FC_maxpay',
            'Consumption_month12_保险/理财_maxpay' => 'cons_m12_BXLC_maxpay',
            'Consumption_level_其他' => 'cons_m12_QT_level',
            'Consumption_level_服装配饰' => 'cons_m12_FZPS_level',
            'Consumption_level_鞋' => 'cons_m12_X_level',
            'Consumption_level_母婴用品' => 'cons_m12_MYYP_level',
            'Consumption_level_文化娱乐' => 'cons_m12_WHYL_level',
            'Consumption_level_运动户外' => 'cons_m12_YDHW_level',
            'Consumption_level_日用百货' => 'cons_m12_RYBH_level',
            'Consumption_level_个护化妆' => 'cons_m12_GHHZ_level',
            'Consumption_level_箱包' => 'cons_m12_XB_level',
            'Consumption_level_手机/手机配件' => 'cons_m12_SJSJPJ_level',
            'Consumption_level_电脑/办公' => 'cons_m12_DNBG_level',
            'Consumption_level_美食特产' => 'cons_m12_MSTC_level',
            'Consumption_level_家具建材' => 'cons_m12_JJJC_level',
            'Consumption_level_通讯' => 'cons_m12_TX_level',
            'Consumption_level_家用电器' => 'cons_m12_JYDQ_level',
            'Consumption_level_家居家纺' => 'cons_m12_JJJF_level',
            'Consumption_level_数码' => 'cons_m12_SM_level',
            'Consumption_level_钟表首饰' => 'cons_m12_ZBSS_level',
            'Consumption_level_汽车用品' => 'cons_m12_QCYP_level',
            'Consumption_level_网络游戏/虚拟物品' => 'cons_m12_WLYXXNYP_level',
            'Consumption_level_医疗保健' => 'cons_m12_YLBJ_level',
            'Consumption_level_本地生活' => 'cons_m12_BDSH_level',
            'Consumption_level_珠宝贵金属' => 'cons_m12_ZBGJS_level',
            'Consumption_level_收藏' => 'cons_m12_SJ_level',
            'Consumption_level_宠物生活' => 'cons_m12_CWSH_level',
            'Consumption_level_出差旅游' => 'cons_m12_CCLY_level',
            'Consumption_level_教育培训' => 'cons_m12_JYPX_level',
            'Consumption_level_房产' => 'cons_m12_FC_level',
            'Consumption_level_保险/理财' => 'cons_m12_BXLC_level',
            'Consumption_c_continue' => 'cons_cont',
            'Consumption_c_time_recent' => 'cons_time_recent',
            'Consumption_c_total_month3_number' => 'cons_tot_m3_num',
            'Consumption_c_total_month3_pay' => 'cons_tot_m3_pay',
            'Consumption_c_total_month3_p_catenum' => 'cons_tot_m3_p_catenum',
            'Consumption_c_total_month3_v_catenum' => 'cons_tot_m3_v_catenum',
            'Consumption_c_total_month3_visits' => 'cons_tot_m3_visits',
            'Consumption_c_total_month12_number' => 'cons_tot_m12_num',
            'Consumption_c_total_month12_pay' => 'cons_tot_m12_pay',
            'Consumption_c_total_month12_p_catenum' => 'cons_tot_m12_p_catenum',
            'Consumption_c_total_month12_v_catenum' => 'cons_tot_m12_v_catenum',
            'Consumption_c_total_month12_visits' => 'cons_tot_m12_visits',
            'Consumption_c_max_month3_number' => 'cons_max_m3_num',
            'Consumption_c_max_month3_pay' => 'cons_max_m3_pay',
            'Consumption_c_max_month3_paycate' => 'cons_max_m3_paycate',
            'Consumption_c_max_month12_number' => 'cons_max_m12_num',
            'Consumption_c_max_month12_pay' => 'cons_max_m12_pay',
            'Consumption_c_max_month12_paycate' => 'cons_max_m12_paycate',
            'Consumption_c_month3_日用百货_number' => 'cons_m3_RYBH_num',
            'Consumption_c_month3_日用百货_pay' => 'cons_m3_RYBH_pay',
            'Consumption_c_month3_家用电器_number' => 'cons_m3_JYDQ_num',
            'Consumption_c_month3_家用电器_pay' => 'cons_m3_JYDQ_pay',
            'Consumption_c_month3_母婴用品_number' => 'cons_m3_MYYP_num',
            'Consumption_c_month3_母婴用品_pay' => 'cons_m3_MYYP_pay',
            'Consumption_c_month12_日用百货_number' => 'cons_m12_RYBH_num',
            'Consumption_c_month12_日用百货_pay' => 'cons_m12_RYBH_pay',
            'Consumption_c_month12_家用电器_number' => 'cons_m12_JYDQ_num',
            'Consumption_c_month12_家用电器_pay' => 'cons_m12_JYDQ_pay',
            'Consumption_c_month12_母婴用品_number' => 'cons_m12_MYYP_num',
            'Consumption_c_month12_母婴用品_pay' => 'cons_m12_MYYP_pay',

            'Location_home_addr_addr11' => 'location_home_addr1',
            'Location_home_addr_addr12' => 'location_home_addr2',
            'Location_home_addr_addr13' => 'location_home_addr3',
            'Location_home_addr_addr14' => 'location_home_addr4',
            'Location_home_addr_addr15' => 'location_home_addr5',
            'Location_biz_addr_addr21' => 'location_biz_addr1',
            'Location_biz_addr_addr22' => 'location_biz_addr2',
            'Location_biz_addr_addr23' => 'location_biz_addr3',
            'Location_biz_addr_addr24' => 'location_biz_addr4',
            'Location_biz_addr_addr25' => 'location_biz_addr5',
            'Location_per_addr_addr31' => 'location_per_addr1',
            'Location_per_addr_addr32' => 'location_per_addr2',
            'Location_per_addr_addr33' => 'location_per_addr3',
            'Location_per_addr_addr34' => 'location_per_addr4',
            'Location_per_addr_addr35' => 'location_per_addr5',
            'Location_apply_addr_addr41' => 'location_apply_addr1',
            'Location_apply_addr_addr42' => 'location_apply_addr2',
            'Location_apply_addr_addr43' => 'location_apply_addr3',
            'Location_apply_addr_addr44' => 'location_apply_addr4',
            'Location_apply_addr_addr45' => 'location_apply_addr5',
            'Location_oth_addr_addr51' => 'location_oth_addr1',
            'Location_oth_addr_addr52' => 'location_oth_addr2',
            'Location_oth_addr_addr53' => 'location_oth_addr3',
            'Location_oth_addr_addr54' => 'location_oth_addr4',
            'Location_oth_addr_addr55' => 'location_oth_addr5',


            'Media_month3_其他_visitdays' => 'media_m3_QT_visitdays',
            'Media_month3_财经_visitdays' => 'media_m3_CJ_visitdays',
            'Media_month3_交友_visitdays' => 'media_m3_JYOU_visitdays',
            'Media_month3_军事_visitdays' => 'media_m3_JS_visitdays',
            'Media_month3_彩票_visitdays' => 'media_m3_CP_visitdays',
            'Media_month3_旅游_visitdays' => 'media_m3_LY_visitdays',
            'Media_month3_女性时尚_visitdays' => 'media_m3_NXSS_visitdays',
            'Media_month3_汽车_visitdays' => 'media_m3_QC_visitdays',
            'Media_month3_社区_visitdays' => 'media_m3_SQ_visitdays',
            'Media_month3_生活_visitdays' => 'media_m3_SH_visitdays',
            'Media_month3_视频_visitdays' => 'media_m3_SP_visitdays',
            'Media_month3_IT_visitdays' => 'media_m3_IT_visitdays',
            'Media_month3_数码_visitdays' => 'media_m3_SM_visitdays',
            'Media_month3_手机_visitdays' => 'media_m3_SJ_visitdays',
            'Media_month3_体育_visitdays' => 'media_m3_TY_visitdays',
            'Media_month3_游戏_visitdays' => 'media_m3_YXI_visitdays',
            'Media_month3_文学艺术_visitdays' => 'media_m3_WXYS_visitdays',
            'Media_month3_新闻_visitdays' => 'media_m3_XW_visitdays',
            'Media_month3_音乐_visitdays' => 'media_m3_YYUE_visitdays',
            'Media_month3_支付_visitdays' => 'media_m3_YF_visitdays',
            'Media_month3_影视_visitdays' => 'media_m3_YS_visitdays',
            'Media_month3_邮箱_visitdays' => 'media_m3_YXIANG_visitdays',
            'Media_month3_招聘_visitdays' => 'media_m3_ZP_visitdays',
            'Media_month3_教育_visitdays' => 'media_m3_JYU_visitdays',
            'Media_month3_房产_visitdays' => 'media_m3_FC_visitdays',
            'Media_month3_应用_visitdays' => 'media_m3_YYONG_visitdays',
            'Media_month3_动漫_visitdays' => 'media_m3_DM_visitdays',
            'Media_month3_美食_visitdays' => 'media_m3_MS_visitdays',
            'Media_month3_母婴/育儿_visitdays' => 'media_m3_MYYE_visitdays',
            'Media_month3_知识问答_visitdays' => 'media_m3_ZSWD_visitdays',
            'Media_month3_娱乐_visitdays' => 'media_m3_YL_visitdays',
            'Media_month3_历史_visitdays' => 'media_m3_LS_visitdays',
            'Media_month3_健康_visitdays' => 'media_m3_JK_visitdays',
            'Media_month3_户外_visitdays' => 'media_m3_HW_visitdays',
            'Media_month6_其他_visitdays' => 'media_m6_QT_visitdays',
            'Media_month6_财经_visitdays' => 'media_m6_CJ_visitdays',
            'Media_month6_交友_visitdays' => 'media_m6_JYOU_visitdays',
            'Media_month6_军事_visitdays' => 'media_m6_JS_visitdays',
            'Media_month6_彩票_visitdays' => 'media_m6_CP_visitdays',
            'Media_month6_旅游_visitdays' => 'media_m6_LY_visitdays',
            'Media_month6_女性时尚_visitdays' => 'media_m6_NXSS_visitdays',
            'Media_month6_汽车_visitdays' => 'media_m6_QC_visitdays',
            'Media_month6_社区_visitdays' => 'media_m6_SQ_visitdays',
            'Media_month6_生活_visitdays' => 'media_m6_SH_visitdays',
            'Media_month6_视频_visitdays' => 'media_m6_SP_visitdays',
            'Media_month6_IT_visitdays' => 'media_m6_IT_visitdays',
            'Media_month6_数码_visitdays' => 'media_m6_SM_visitdays',
            'Media_month6_手机_visitdays' => 'media_m6_SJ_visitdays',
            'Media_month6_体育_visitdays' => 'media_m6_TY_visitdays',
            'Media_month6_游戏_visitdays' => 'media_m6_YXI_visitdays',
            'Media_month6_文学艺术_visitdays' => 'media_m6_WXYS_visitdays',
            'Media_month6_新闻_visitdays' => 'media_m6_XW_visitdays',
            'Media_month6_音乐_visitdays' => 'media_m6_YYUE_visitdays',
            'Media_month6_支付_visitdays' => 'media_m6_YF_visitdays',
            'Media_month6_影视_visitdays' => 'media_m6_YS_visitdays',
            'Media_month6_邮箱_visitdays' => 'media_m6_YXIANG_visitdays',
            'Media_month6_招聘_visitdays' => 'media_m6_ZP_visitdays',
            'Media_month6_教育_visitdays' => 'media_m6_JYU_visitdays',
            'Media_month6_房产_visitdays' => 'media_m6_FC_visitdays',
            'Media_month6_应用_visitdays' => 'media_m6_YYONG_visitdays',
            'Media_month6_动漫_visitdays' => 'media_m6_DM_visitdays',
            'Media_month6_美食_visitdays' => 'media_m6_MS_visitdays',
            'Media_month6_母婴/育儿_visitdays' => 'media_m6_MYYE_visitdays',
            'Media_month6_知识问答_visitdays' => 'media_m6_ZSWD_visitdays',
            'Media_month6_娱乐_visitdays' => 'media_m6_YL_visitdays',
            'Media_month6_历史_visitdays' => 'media_m6_LS_visitdays',
            'Media_month6_健康_visitdays' => 'media_m6_JK_visitdays',
            'Media_month6_户外_visitdays' => 'media_m6_HW_visitdays',
            'Media_month12_其他_visitdays' => 'media_m12_QT_visitdays',
            'Media_month12_财经_visitdays' => 'media_m12_CJ_visitdays',
            'Media_month12_交友_visitdays' => 'media_m12_JYOU_visitdays',
            'Media_month12_军事_visitdays' => 'media_m12_JS_visitdays',
            'Media_month12_彩票_visitdays' => 'media_m12_CP_visitdays',
            'Media_month12_旅游_visitdays' => 'media_m12_LY_visitdays',
            'Media_month12_女性时尚_visitdays' => 'media_m12_NXSS_visitdays',
            'Media_month12_汽车_visitdays' => 'media_m12_QC_visitdays',
            'Media_month12_社区_visitdays' => 'media_m12_SQ_visitdays',
            'Media_month12_生活_visitdays' => 'media_m12_SH_visitdays',
            'Media_month12_视频_visitdays' => 'media_m12_SP_visitdays',
            'Media_month12_IT_visitdays' => 'media_m12_IT_visitdays',
            'Media_month12_数码_visitdays' => 'media_m12_SM_visitdays',
            'Media_month12_手机_visitdays' => 'media_m12_SJ_visitdays',
            'Media_month12_体育_visitdays' => 'media_m12_TY_visitdays',
            'Media_month12_游戏_visitdays' => 'media_m12_YXI_visitdays',
            'Media_month12_文学艺术_visitdays' => 'media_m12_WXYS_visitdays',
            'Media_month12_新闻_visitdays' => 'media_m12_XW_visitdays',
            'Media_month12_音乐_visitdays' => 'media_m12_YYUE_visitdays',
            'Media_month12_支付_visitdays' => 'media_m12_YF_visitdays',
            'Media_month12_影视_visitdays' => 'media_m12_YS_visitdays',
            'Media_month12_邮箱_visitdays' => 'media_m12_YXIANG_visitdays',
            'Media_month12_招聘_visitdays' => 'media_m12_ZP_visitdays',
            'Media_month12_教育_visitdays' => 'media_m12_JYU_visitdays',
            'Media_month12_房产_visitdays' => 'media_m12_FC_visitdays',
            'Media_month12_应用_visitdays' => 'media_m12_YYONG_visitdays',
            'Media_month12_动漫_visitdays' => 'media_m12_DM_visitdays',
            'Media_month12_美食_visitdays' => 'media_m12_MS_visitdays',
            'Media_month12_母婴/育儿_visitdays' => 'media_m12_MYYE_visitdays',
            'Media_month12_知识问答_visitdays' => 'media_m12_ZSWD_visitdays',
            'Media_month12_娱乐_visitdays' => 'media_m12_YL_visitdays',
            'Media_month12_历史_visitdays' => 'media_m12_LS_visitdays',
            'Media_month12_健康_visitdays' => 'media_m12_JK_visitdays',
            'Media_month12_户外_visitdays' => 'media_m12_HW_visitdays',


            'Media_c_total_month3_visitdays' => 'media_tot_m3_days',
            'Media_c_total_month12_visitdays' => 'media_tot_m12_days',
            'Media_c_max_month3_days_prop' => 'media_max_m3_days_prop',
            'Media_c_max_month12_days_prop' => 'media_max_m12_days_prop',
            'Media_c_max_month3_visitdays' => 'media_max_m3_days',
            'Media_c_max_month3_cate' => 'media_max_m3_cate',
            'Media_c_max_month12_visitdays' => 'media_max_m12_days',
            'Media_c_max_month12_cate' => 'media_max_m12_cate',
            'Media_c_total_month3_catenum' => 'media_tot_m3_catenum',
            'Media_c_total_month12_catenum' => 'media_tot_m12_catenum',
            'Media_c_month3_财经_visitdays' => 'media_m3_CJ_visitdays',
            'Media_c_month3_文学艺术_visitdays' => 'media_m3_WXYS_visitdays',
            'Media_c_month3_母婴/育儿_visitdays' => 'media_m3_MYYE_visitdays',
            'Media_c_month12_财经_visitdays' => 'media_m12_CJ_visitdays',
            'Media_c_month12_文学艺术_visitdays' => 'media_m12_WXYS_visitdays',
            'Media_c_month12_母婴/育儿_visitdays' => 'mediac_m12_MYYE_visitdays',


            'PayConsumption_thm1_pay' => 'pc_thm1_pay',
            'PayConsumption_thm1_number' => 'pc_thm1_num',
            'PayConsumption_thm1_first_payMcc' => 'pc_thm1_1st_pay_mcc',
            'PayConsumption_thm1_first_numberMcc' => 'pc_thm1_1st_num_mcc',
            'PayConsumption_thm1_second_numberMcc' => 'pc_thm1_2nd_num_mcc',
            'PayConsumption_thm1_second_payMcc' => 'pc_thm1_2nd_pay_mcc',
            'PayConsumption_thm1_third_numberMcc' => 'pc_thm1_3rd_num_mcc',
            'PayConsumption_thm1_third_payMcc' => 'pc_thm1_3rd_pay_mcc',
            'PayConsumption_thm1_maxNumberProvince' => 'pc_thm1_max_num_pvn',
            'PayConsumption_thm1_night_number' => 'pc_thm1_night_num',
            'PayConsumption_thm1_night_pay' => 'pc_thm1_night_pay',
            'PayConsumption_thm2_pay' => 'pc_thm2_pay',
            'PayConsumption_thm2_number' => 'pc_thm2_num',
            'PayConsumption_thm2_first_payMcc' => 'pc_thm2_1st_pay_mcc',
            'PayConsumption_thm2_first_numberMcc' => 'pc_thm2_1st_num_mcc',
            'PayConsumption_thm2_second_numberMcc' => 'pc_thm2_2nd_num_mcc',
            'PayConsumption_thm2_second_payMcc' => 'pc_thm2_2nd_pay_mcc',
            'PayConsumption_thm2_third_numberMcc' => 'pc_thm2_3rd_num_mcc',
            'PayConsumption_thm2_third_payMcc' => 'pc_thm2_3rd_pay_mcc',
            'PayConsumption_thm2_maxNumberProvince' => 'pc_thm2_max_num_pvn',
            'PayConsumption_thm2_night_number' => 'pc_thm2_night_num',
            'PayConsumption_thm2_night_pay' => 'pc_thm2_night_pay',
            'PayConsumption_thm3_pay' => 'pc_thm3_pay',
            'PayConsumption_thm3_number' => 'pc_thm3_num',
            'PayConsumption_thm3_first_payMcc' => 'pc_thm3_1st_pay_mcc',
            'PayConsumption_thm3_first_numberMcc' => 'pc_thm3_1st_num_mcc',
            'PayConsumption_thm3_second_numberMcc' => 'pc_thm3_2nd_num_mcc',
            'PayConsumption_thm3_second_payMcc' => 'pc_thm3_2nd_pay_mcc',
            'PayConsumption_thm3_third_numberMcc' => 'pc_thm3_3rd_num_mcc',
            'PayConsumption_thm3_third_payMcc' => 'pc_thm3_3rd_pay_mcc',
            'PayConsumption_thm3_maxNumberProvince' => 'pc_thm3_max_num_pvn',
            'PayConsumption_thm3_night_number' => 'pc_thm3_night_num',
            'PayConsumption_thm3_night_pay' => 'pc_thm3_night_pay',
            'PayConsumption_thm4_pay' => 'pc_thm4_pay',
            'PayConsumption_thm4_number' => 'pc_thm4_num',
            'PayConsumption_thm4_first_payMcc' => 'pc_thm4_1st_pay_mcc',
            'PayConsumption_thm4_first_numberMcc' => 'pc_thm4_1st_num_mcc',
            'PayConsumption_thm4_second_numberMcc' => 'pc_thm4_2nd_num_mcc',
            'PayConsumption_thm4_second_payMcc' => 'pc_thm4_2nd_pay_mcc',
            'PayConsumption_thm4_third_numberMcc' => 'pc_thm4_3rd_num_mcc',
            'PayConsumption_thm4_third_payMcc' => 'pc_thm4_3rd_pay_mcc',
            'PayConsumption_thm4_maxNumberProvince' => 'pc_thm4_max_num_pvn',
            'PayConsumption_thm4_night_number' => 'pc_thm4_night_num',
            'PayConsumption_thm4_night_pay' => 'pc_thm4_night_pay',
            'PayConsumption_thm5_pay' => 'pc_thm5_pay',
            'PayConsumption_thm5_number' => 'pc_thm5_num',
            'PayConsumption_thm5_first_payMcc' => 'pc_thm5_1st_pay_mcc',
            'PayConsumption_thm5_first_numberMcc' => 'pc_thm5_1st_num_mcc',
            'PayConsumption_thm5_second_numberMcc' => 'pc_thm5_2nd_num_mcc',
            'PayConsumption_thm5_second_payMcc' => 'pc_thm5_2nd_pay_mcc',
            'PayConsumption_thm5_third_numberMcc' => 'pc_thm5_3rd_num_mcc',
            'PayConsumption_thm5_third_payMcc' => 'pc_thm5_3rd_pay_mcc',
            'PayConsumption_thm5_maxNumberProvince' => 'pc_thm5_max_num_pvn',
            'PayConsumption_thm5_night_number' => 'pc_thm5_night_num',
            'PayConsumption_thm5_night_pay' => 'pc_thm5_night_pay',
            'PayConsumption_thm6_pay' => 'pc_thm6_pay',
            'PayConsumption_thm6_number' => 'pc_thm6_num',
            'PayConsumption_thm6_first_payMcc' => 'pc_thm6_1st_pay_mcc',
            'PayConsumption_thm6_first_numberMcc' => 'pc_thm6_1st_num_mcc',
            'PayConsumption_thm6_second_numberMcc' => 'pc_thm6_2nd_num_mcc',
            'PayConsumption_thm6_second_payMcc' => 'pc_thm6_2rd_pay_mcc',
            'PayConsumption_thm6_third_numberMcc' => 'pc_thm6_3rd_num_mcc',
            'PayConsumption_thm6_third_payMcc' => 'pc_thm6_3rd_pay_mcc',
            'PayConsumption_thm6_maxNumberProvince' => 'pc_thm6_max_num_pvn',
            'PayConsumption_thm6_night_number' => 'pc_thm6_night_num',
            'PayConsumption_thm6_night_pay' => 'pc_thm6_night_pay',
            'PayConsumption_thm7_pay' => 'pc_thm7_pay',
            'PayConsumption_thm7_number' => 'pc_thm7_num',
            'PayConsumption_thm7_first_payMcc' => 'pc_thm7_1st_pay_mcc',
            'PayConsumption_thm7_first_numberMcc' => 'pc_thm7_1st_num_mcc',
            'PayConsumption_thm7_second_numberMcc' => 'pc_thm7_2nd_pay_mcc',
            'PayConsumption_thm7_second_payMcc' => 'pc_thm7_2nd_num_mcc',
            'PayConsumption_thm7_third_numberMcc' => 'pc_thm7_3rd_num_mcc',
            'PayConsumption_thm7_third_payMcc' => 'pc_thm7_3rd_pay_mcc',
            'PayConsumption_thm7_maxNumberProvince' => 'pc_thm7_max_num_pvn',
            'PayConsumption_thm7_night_number' => 'pc_thm7_night_num',
            'PayConsumption_thm7_night_pay' => 'pc_thm7_night_pay',
            'PayConsumption_thm8_pay' => 'pc_thm8_pay',
            'PayConsumption_thm8_number' => 'pc_thm8_num',
            'PayConsumption_thm8_first_payMcc' => 'pc_thm8_1st_pay_mcc',
            'PayConsumption_thm8_first_numberMcc' => 'pc_thm8_1st_num_mcc',
            'PayConsumption_thm8_second_numberMcc' => 'pc_thm8_2nd_num_mcc',
            'PayConsumption_thm8_second_payMcc' => 'pc_thm8_2nd_pay_mcc',
            'PayConsumption_thm8_third_numberMcc' => 'pc_thm8_3rd_num_mcc',
            'PayConsumption_thm8_third_payMcc' => 'pc_thm8_3rd_pay_mcc',
            'PayConsumption_thm8_maxNumberProvince' => 'pc_thm8_max_num_pvn',
            'PayConsumption_thm8_night_number' => 'pc_thm8_night_num',
            'PayConsumption_thm8_night_pay' => 'pc_thm8_night_pay',
            'PayConsumption_thm9_pay' => 'pc_thm9_pay',
            'PayConsumption_thm9_number' => 'pc_thm9_num',
            'PayConsumption_thm9_first_payMcc' => 'pc_thm9_1st_pay_mcc',
            'PayConsumption_thm9_first_numberMcc' => 'pc_thm9_1st_num_mcc',
            'PayConsumption_thm9_second_numberMcc' => 'pc_thm9_2nd_num_mcc',
            'PayConsumption_thm9_second_payMcc' => 'pc_thm9_2nd_pay_mcc',
            'PayConsumption_thm9_third_numberMcc' => 'pc_thm9_3rd_num_mcc',
            'PayConsumption_thm9_third_payMcc' => 'pc_thm9_3rd_pay_mcc',
            'PayConsumption_thm9_maxNumberProvince' => 'pc_thm9_max_num_pvn',
            'PayConsumption_thm9_night_number' => 'pc_thm9_night_num',
            'PayConsumption_thm9_night_pay' => 'pc_thm9_night_pay',
            'PayConsumption_thm10_pay' => 'pc_thm10_pay',
            'PayConsumption_thm10_number' => 'pc_thm10_num',
            'PayConsumption_thm10_first_payMcc' => 'pc_thm10_1st_pay_mcc',
            'PayConsumption_thm10_first_numberMcc' => 'pc_thm10_1st_num_mcc',
            'PayConsumption_thm10_second_numberMcc' => 'pc_thm10_2nd_num_mcc ',
            'PayConsumption_thm10_second_payMcc' => 'pc_thm10_2nd_pay_mcc',
            'PayConsumption_thm10_third_numberMcc' => 'pc_thm10_3rd_num_mcc',
            'PayConsumption_thm10_third_payMcc' => 'pc_thm10_3rd_pay_mcc',
            'PayConsumption_thm10_maxNumberProvince' => 'pc_thm10_max_num_pvn',
            'PayConsumption_thm10_night_number' => 'pc_thm10_night_num',
            'PayConsumption_thm10_night_pay' => 'pc_thm10_night_pay',
            'PayConsumption_thm11_pay' => 'pc_thm11_pay',
            'PayConsumption_thm11_number' => 'pc_thm11_num',
            'PayConsumption_thm11_first_payMcc' => 'pc_thm11_1st_pay_mcc',
            'PayConsumption_thm11_first_numberMcc' => 'pc_thm11_1st_num_mcc',
            'PayConsumption_thm11_second_numberMcc' => 'pc_thm11_2nd_pay_mcc',
            'PayConsumption_thm11_second_payMcc' => 'pc_thm11_2rd_pay_mcc',
            'PayConsumption_thm11_third_numberMcc' => 'pc_thm11_3rd_num_mcc',
            'PayConsumption_thm11_third_payMcc' => 'pc_thm11_3rd_pay_mcc',
            'PayConsumption_thm11_maxNumberProvince' => 'pc_thm11_max_num_pvn',
            'PayConsumption_thm11_night_number' => 'pc_thm11_night_num',
            'PayConsumption_thm11_night_pay' => 'pc_thm11_night_pay',
            'PayConsumption_thm12_pay' => 'pc_thm12_pay',
            'PayConsumption_thm12_number' => 'pc_thm12_num',
            'PayConsumption_thm12_first_payMcc' => 'pc_thm12_1st_pay_mcc',
            'PayConsumption_thm12_first_numberMcc' => 'pc_thm12_1st_num_mcc',
            'PayConsumption_thm12_second_numberMcc' => 'pc_thm12_2nd_num_mcc',
            'PayConsumption_thm12_second_payMcc' => 'pc_thm12_2nd_pay_mcc',
            'PayConsumption_thm12_third_numberMcc' => 'pc_thm12_3rd_num_mcc',
            'PayConsumption_thm12_third_payMcc' => 'pc_thm12_3rd_pay_mcc',
            'PayConsumption_thm12_maxNumberProvince' => 'pc_thm12_max_num_pvn',
            'PayConsumption_thm12_night_number' => 'pc_thm12_night_num',
            'PayConsumption_thm12_night_pay' => 'pc_thm12_night_pay',

            'Rating_p2pConsumeRating' => 'rating_p2p_consume',
            'Rating_p2pMediaRating' => 'rating_p2p_media',
            'Rating_p2pBrcrerditRating' => 'rating_p2p_br_credit',
            'RuleResult_stability_highRisk' => 'ruleresult_stability',
            'RuleResult_consumption_highRisk' => 'ruleresult_consumption',
            'SpecialList_id_A1_degree' => 'sl_id_A1_degree',
            'SpecialList_id_A2_degree' => 'sl_id_A2_degree',
            'SpecialList_id_A3_degree' => 'sl_id_A3_degree',
            'SpecialList_id_A5_degree' => 'sl_id_A5_degree',
            'SpecialList_id_A6_degree' => 'sl_id_A6_degree',
            'SpecialList_id_A7_degree' => 'sl_id_A7_degree',
            'SpecialList_id_B1_degree' => 'sl_id_B1_degree',
            'SpecialList_id_B2_degree' => 'sl_id_B2_degree',
            'SpecialList_id_B3_degree' => 'sl_id_B3_degree',
            'SpecialList_id_B5_degree' => 'sl_id_B5_degree',
            'SpecialList_id_B6_degree' => 'sl_id_B6_degree',
            'SpecialList_id_C1_degree' => 'sl_id_C1_degree',
            'SpecialList_id_D1_degree' => 'sl_id_D1_degree',
            'SpecialList_id_E1_degree' => 'sl_id_E1_degree',
            'SpecialList_id_E2_degree' => 'sl_id_E2_degree',
            'SpecialList_cell_A1_degree' => 'sl_cell_A1_degree',
            'SpecialList_cell_A2_degree' => 'sl_cell_A2_degree',
            'SpecialList_cell_A3_degree' => 'sl_cell_A3_degree',
            'SpecialList_cell_A5_degree' => 'sl_cell_A5_degree',
            'SpecialList_cell_A6_degree' => 'sl_cell_A6_degree',
            'SpecialList_cell_A7_degree' => 'sl_cell_A7_degree',
            'SpecialList_cell_B1_degree' => 'sl_cell_B1_degree',
            'SpecialList_cell_B2_degree' => 'sl_cell_B2_degree',
            'SpecialList_cell_B3_degree' => 'sl_cell_B3_degree',
            'SpecialList_cell_B5_degree' => 'sl_cell_B5_degree',
            'SpecialList_cell_B6_degree' => 'sl_cell_B6_degree',
            'SpecialList_cell_C1_degree' => 'sl_cell_C1_degree',
            'SpecialList_cell_D1_degree' => 'sl_cell_D1_degree',
            'SpecialList_cell_E1_degree' => 'sl_cell_E1_degree',
            'SpecialList_cell_E2_degree' => 'sl_cell_E2_degree',
            'SpecialList_gid_A1_degree' => 'sl_gid_A1_degree',
            'SpecialList_gid_A2_degree' => 'sl_gid_A2_degree',
            'SpecialList_gid_A3_degree' => 'sl_gid_A3_degree',
            'SpecialList_gid_A5_degree' => 'sl_gid_A5_degree',
            'SpecialList_gid_A6_degree' => 'sl_gid_A6_degree',
            'SpecialList_gid_A7_degree' => 'sl_gid_A7_degree',
            'SpecialList_gid_B1_degree' => 'sl_gid_B1_degree',
            'SpecialList_gid_B2_degree' => 'sl_gid_B2_degree',
            'SpecialList_gid_B3_degree' => 'sl_gid_B3_degree',
            'SpecialList_gid_B5_degree' => 'sl_gid_B5_degree',
            'SpecialList_gid_B6_degree' => 'sl_gid_B6_degree',
            'SpecialList_gid_C1_degree' => 'sl_gid_C1_degree',
            'SpecialList_gid_D1_degree' => 'sl_gid_D1_degree',
            'SpecialList_gid_E1_degree' => 'sl_gid_E1_degree',
            'SpecialList_gid_E2_degree' => 'sl_gid_E2_degree',

            'SpecialList_c_id_bank_bad' => 'sl_id_bank_bad',
            'SpecialList_c_id_bank_overdue' => 'sl_id_bank_overdue',
            'SpecialList_c_id_bank_fraud' => 'sl_id_bank_fraud',
            'SpecialList_c_id_bank_lost' => 'sl_id_bank_lost',
            'SpecialList_c_id_bank_refuse' => 'sl_id_bank_refuse',
            'SpecialList_c_id_credit_bad' => 'sl_id_credit_bad',
            'SpecialList_c_id_p2p_bad' => 'sl_id_p2p_bad',
            'SpecialList_c_id_p2p_overdue' => 'sl_id_p2p_overdue',
            'SpecialList_c_id_p2p_fraud' => 'sl_id_p2p_fraud',
            'SpecialList_c_id_p2p_lost' => 'sl_id_p2p_lost',
            'SpecialList_c_id_p2p_refuse' => 'sl_id_p2p_refuse',
            'SpecialList_c_id_phone_overdue' => 'sl_id_phone_overdue',
            'SpecialList_c_id_ins_fraud' => 'sl_id_ins_fraud',
            'SpecialList_c_id_court_bad' => 'sl_id_court_bad',
            'SpecialList_c_id_court__executed' => 'sl_id_court__executed',

            'SpecialList_c_cell_bank_bad' => 'sl_cell_bank_bad',
            'SpecialList_c_cell_bank_overdue' => 'sl_cell_bank_overdue',
            'SpecialList_c_cell_bank_fraud' => 'sl_cell_bank_fraud',
            'SpecialList_c_cell_bank_lost' => 'sl_cell_bank_lost',
            'SpecialList_c_cell_bank_refuse' => 'sl_cell_bank_refuse',
            'SpecialList_c_cell_p2p_bad' => 'sl_cell_p2p_bad',
            'SpecialList_c_cell_p2p_overdue' => 'sl_cell_p2p_overdue',
            'SpecialList_c_cell_p2p_fraud' => 'sl_cell_p2p_fraud',
            'SpecialList_c_cell_p2p_lost' => 'sl_cell_p2p_lost',
            'SpecialList_c_cell_p2p_refuse' => 'sl_cell_p2p_refuse',
            'SpecialList_c_cell_phone_overdue' => 'sl_cell_phone_overdue',
            'SpecialList_c_cell_ins_fraud' => 'sl_cell_ins_fraud',

            'SpecialList_c_gid_bank_bad' => 'sl_gid_bank_bad',
            'SpecialList_c_gid_bank_overdue' => 'sl_gid_bank_overdue',
            'SpecialList_c_gid_bank_fraud' => 'sl_gid_bank_fraud',
            'SpecialList_c_gid_bank_lost' => 'sl_gid_bank_lost',
            'SpecialList_c_gid_bank_refuse' => 'sl_gid_bank_refuse',
            'SpecialList_c_gid_p2p_bad' => 'sl_gid_p2p_bad',
            'SpecialList_c_gid_p2p_overdue' => 'sl_gid_p2p_overdue',
            'SpecialList_c_gid_p2p_fraud' => 'sl_gid_p2p_fraud',
            'SpecialList_c_gid_p2p_lost' => 'sl_gid_p2p_lost',
            'SpecialList_c_gid_p2p_refuse' => 'sl_gid_p2p_refuse',
            'SpecialList_c_gid_phone_overdue' => 'sl_gid_phone_overdue',
            'SpecialList_c_gid_ins_fraud' => 'sl_gid_ins_fraud',



            'Stability_c_Authentication_id-name' => 'stabc_auth_id_name',
            'Stability_c_Authentication_id' => 'stabc_auth_id',
            'Stability_c_Authentication_cell' => 'stabc_auth_cell',
            'Stability_c_Authentication_mail' => 'stabc_auth_mail',
            'Stability_c_Authentication_key_relation' => 'stabc_auth_key_relation',
            'Stability_c_Authentication_home_tel' => 'stabc_auth_home_tel',
            'Stability_c_Authentication_biz_tel' => 'stabc_auth_biz_tel',
            'Stability_c_Authentication_name' => 'stabc_auth_name',
            'Stability_c_id_number' => 'stabc_id_num',
            'Stability_c_cell_firsttime' => 'stabc_cell_firsttime',
            'Stability_c_cell_number' => 'stabc_cell_num',
            'Stability_c_mail_number' => 'stabc_mail_num',
            'Stability_c_name_number' => 'stabc_name_num',
            'Stability_c_tel_number' => 'stabc_tel_num',
            'Stability_c_addr_number' => 'stabc_addr_num',
            'Title_title' => 'title'
        );
    }

    //需要在csv靠前显示字段
    public static function fixSortTitle() {
        return array(
            'flag_accountChange' => '',
            'flag_consumption_c' => '',
            'flag_consumption' => '',
            'flag_specialList' => '',
            'flag_specialList_c' => '',
            'flag_payConsumption' => '',
            'flag_location' => '',
            'flag_telecomCheck' => '',
            'flag_stability_c' => '',
            'flag_applyLoan' => '',
            'flag_accountChangeMonth' => '',
            'flag_media_c' => '',
            'flag_score' => '',
            'flag_datacust' => '',
            'flag_authentication' => '',
            'flag_rulespeciallist' => '',
            'flag_ruleapplyloan' => '',
        );
    }

    public static function defaultFlagTitle(){
        return array(
            'flag_accountChange' => '',
            'flag_consumption_c' => '',
            'flag_consumption' => '',
            'flag_specialList' => '',
            'flag_specialList_c' => '',
            'flag_payConsumption' => '',
            'flag_location' => '',
            'flag_telecomCheck' => '',
            'flag_stability_c' => '',
            'flag_applyLoan' => '',
            'flag_accountChangeMonth' => '',
            'flag_media_c' => '',
            'flag_score' => '',
            'flag_datacust' => '',
            'flag_rulespeciallist' => '',
            'flag_ruleapplyloan' => '',
            'flag_authentication' => ''
        );
    }
    //回收字段 不显示在csv中
    public static function garbageTitle(){
        return array(
            //'code',
            //'swift_number',
            //'Flag_datacust',
            //'Flag_rulespeciallist',
            //'Flag_ruleapplyloan',
            //'DataCust',
            // 'Score_scorecust',
            // 'Score_scorebank',
            //'Score_scorep2p',
            // 'Score_scorecf'
            'Consumption_c_month3',
            'Consumption_c_month12'

        );
    }


};