<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/5/13
 * Time: 下午6:19
 */
class Controller_Index extends Controller{

    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
    }


    public function action_Index(){
        echo json_encode(
            array(
                    'service'=>'Client API',
                    'client'=>array('Android','iOS','Wechat')
                )
        );
        exit;
    }




}









