<?php
defined('SYSPATH') or die('No direct script access.');

/**
 * Created by PhpStorm.
 * User: majin
 * Date: 16/5/13
 * Time: 下午6:19
 */
class Controller_Ver1_Info extends AppCore
{


    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }


    public function action_Index()
    {
        $res =  [
                'service' => 'info',
                'client' => ['Android', 'iOS', 'Wechat'],
                'user' => App::$_user,
                'app_info' => isset($_SERVER['HTTP_APP_INFO']) ? $_SERVER['HTTP_APP_INFO'] : '',
            ];

        $this->response_json($res, "1000", "成功");

    }

    public function action_Auth(){
        $string = $this->_data['_token'];

        $res = [];

        if(Lib::factory('Target_Token')->auth($string)){
            $res =  [
                'service' => 'info',
                'client' => ['Android', 'iOS', 'Wechat'],
                'user' => App::$_user,
                'app_info' => isset($_SERVER['HTTP_APP_INFO']) ? $_SERVER['HTTP_APP_INFO'] : '',
            ];
            $this->response_json($res, "1000", "成功");

        }else{
            $this->response_json($res, "5000", "验证失败");

        }

    }


    public function action_View()
    {
        $view = View::factory($this->_vv.'/Info');
        echo 'app_info:',$_SERVER['HTTP_APP_INFO'];
        echo '<pre>';
        var_dump(App::$_user);
        echo '</pre>';
        $this->response->body($view);
    }

    public function action_View2()
    {

        $_token = Lib::factory('Target_Token')->make();
        $view = View::factory($this->_vv.'/Info2');
        $view->_token = $_token;
        echo 'app_info:',$_SERVER['HTTP_APP_INFO'];

        echo '<pre>';
        var_dump(App::$_user);
        echo '</pre>';

        $this->response->body($view);
    }

}
