<?php
defined('SYSPATH') or die('No direct script access.');
/**
 * Created by PhpStorm.
 * Permission: majin
 * Date: 15/12/23
 * Time: 上午9:20
 *
 * 菜单管理
 *
 */
class Controller_Admin_Menu extends AdminController {

    //权限映射
    var $permission_array = array(
        'map' => array(
                    'List' => array('Index','Add','Edit','Delete')
                )
    );


    var $menu_tree = NULL;
    var $menu_lib = NULL;


    public function before() {
        parent::before(); // TODO: Change the autogenerated stub
        $this->init();
    }

    public function init(){
        $this->menu_tree = Model::factory('Admin_Menu')->getTree();
        $this->menu_lib = Model::factory('Admin_Menu')->getAll();
    }


    public function action_Index() {
        $this->action_List();
    }



    public function action_List() {

        $page = isset($this->get['page']) ? intval($this->get['page']):1;
        $perpage = isset($this->get['pagesize']) ? intval($this->get['pagesize']):20;
        $array = array();
        if(array_key_exists('fid',$this->get)) {
            $array['fid'] = intval($this->get['fid']);
        }
        if(array_key_exists('name',$this->get)) {
            $array['name'] = trim($this->get['name']);
        }
        if(array_key_exists('url',$this->get)) {
            $array['url'] = trim($this->get['url']);
        }
        if(array_key_exists('controller',$this->get)) {
            $array['controller'] = trim($this->get['controller']);
        }
        if(array_key_exists('action',$this->get)) {
            $array['action'] = trim($this->get['action']);
        }
        $total = Model::factory('Admin_Menu')->getTotal($array);
        $pagination = Pagination::factory(
            array(
                'total_items' => $total,
                'items_per_page' => $perpage,
            ));
        $list = Model::factory('Admin_Menu')->getList($array, $perpage , $page);
        $menu_lib = Model::factory('Admin_Menu')->getAll();


        Template::factory('Admin/Menu/List',array(
                'menu_tree'=>$this->menu_tree,
                'menu_lib'=>$this->menu_lib,
                'list'=>$list,
                'pagination'=>$pagination,
            )
        )->response();
    }


    public function action_Edit() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $data  = Model::factory('Admin_Menu')->getOne($id);
        if(!$data){
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'信息不存在',
                    'message'=>'信息不存在或已经被删除.',
                    'back'=>TRUE,)
            );
        }
        $user_group = Model::factory('Admin_Group')->getAll();
        if(isset($this->post['submit'])) {
            $valid = Validation::factory($this->post)
                ->rule('name','not_empty')
                ->rule('url','not_empty');
            if($valid->check()) {
                $edit = Model::factory('Admin_Menu')->update($id,array(
                    'fid'=>$this->post['fid'],
                    'name'=>$this->post['name'],
                    'url'=>$this->post['url'],
                    'controller'=>$this->post['controller'],
                    'action'=>$this->post['action'],
                    'pub_show'=>$this->post['pub_show'],
                    'group_show'=>$this->post['group_show'],
                    'sort'=>$this->post['sort'],
                    'description'=>$this->post['description'],
                ));
                if($edit) {
                    $message = array('type' => 'success', 'message' => '更新成功.');
                    $this->init();
                    $data  = Model::factory('Admin_Menu')->getOne($id);//更新输出数据
                }else {
                    $message = array('type' => 'error', 'message' => '更改失败,数据异常.');
                }
            }else {
                $message = array('type' => 'error', 'message' => '更改失败,请查看是否有必填信息未填.');
            }
        }

        Template::factory('Admin/Menu/Edit',array(
            'message'=>$message,
            'menu_tree'=>$this->menu_tree,
            'menu_lib'=>$this->menu_lib,
            'user_group'=>$user_group,
            'data'=>$data,
        ))->response();
    }



    public function action_Add() {
        $message = NULL;
        $data['fid'] = isset($this->get['fid']) ? intval($this->get['fid']):0;
        $user_group = Model::factory('Admin_Group')->getAll();
        if(isset($this->post['submit'])) {
            $valid = Validation::factory($this->post)
                ->rule('name','not_empty')
                ->rule('url','not_empty');
            if($valid->check()) {
                $add = Model::factory('Admin_Menu')->create(array(
                    'fid'=>$this->post['fid'],
                    'name'=>$this->post['name'],
                    'url'=>$this->post['url'],
                    'controller'=>$this->post['controller'],
                    'action'=>$this->post['action'],
                    'pub_show'=>$this->post['pub_show'],
                    'group_show'=>$this->post['group_show'],
                    'sort'=>$this->post['sort'],
                    'description'=>$this->post['description'],
                ));
                if($add) {
                    $message = array('type' => 'success', 'message' => '添加成功.');
                    $this->init();
                }else {
                    $message = array('type' => 'error', 'message' => '添加失败.');
                }
            }else {
                $message = array('type' => 'error', 'message' => '添加失败,请查看是否有必填信息未填.');
            }
        }

        Template::factory('Admin/Menu/Add',array(
            'message'=>$message,
            'menu_tree'=>$this->menu_tree,
            'menu_lib'=>$this->menu_lib,
            'user_group'=>$user_group,
            'data'=>$data
        ))->response();
    }






    public function action_Delete() {
        $message = NULL;
        $id = isset($this->get['id']) ? intval($this->get['id']):0;
        $rs  = Model::factory('Admin_Menu')->getOne($id);
        if(!$rs){
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'信息不存在',
                    'message'=>'信息不存在或已经被删除.',
                    'back'=>TRUE,)
            );
        }
        $son  = Model::factory('Admin_Menu')->getSon($id);
        if($son){
            Template::factory()->message(
                array(
                    'type'=>'error',
                    'title'=>'删除失败',
                    'message'=>'该菜单下存在子菜单,请先删除子菜单.',
                    'back'=>TRUE,)
            );
        }
        $del = Model::factory('Admin_Menu')->delete($id);
        if($del){
            Template::factory()->message(
                array(
                    'type'=>'success',
                    'title'=>'删除成功',
                    'message'=>'菜单:'.$rs['name'].' 被成功删除.',
                    'redirect'=> $this->request->referrer()? $this->request->referrer() :'/'.$this->controller.'/List',
                    'redirect_time'=>3,
                    'back'=>FALSE)
            );
        }
        Template::factory()->message(
            array(
                'type'=>'error',
                'title'=>'删除失败',
                'message'=>'菜单:'.$rs['name'].' 删除未成功,请核实或联系技术人员处理.',
                'back'=>TRUE,)
        );



    }






}